#!/bin/sh

ID_VENDOR="0x2257"
ID_PRODUCT="0x4e42"

USB_DEV_FFS=/dev/usb-ffs
ADB_DEV_DIR=$USB_DEV_FFS/adb

DEV_SNUM=$(head -c 4 /dev/urandom | od -A n -t x | tr -d ' ')

DISABLE_ADBD="/root/.disableadb"
if [ -f $DISABLE_ADBD ]; then
	echo "Because of the existence of [$DISABLE_ADBD] file, adb is not enabled"
	exit 0
fi

case "$1" in
	start)
		printf "Starting adbd:"
		lsmod | grep g_ffs > /dev/null
		if [ $? -ne 0 ]; then
			insmod /lib/modules/g_ffs.ko idVendor=$ID_VENDOR idProduct=$ID_PRODUCT iSerialNumber=$DEV_SNUM
		fi
		[ -d ${ADB_DEV_DIR} ] || mkdir -p ${ADB_DEV_DIR}
		[ "$(ls -A $ADB_DEV_DIR)" != "" ] || mount -t functionfs adb $ADB_DEV_DIR -o uid=2000,gid=2000
		sleep 1
		adbd &
		echo "OK"
		;;
	stop)
		printf "Stoping adbd:"
		killall adbd
		sleep 1
		if [ -d "$USB_DEV_FFS" ]; then
			umount ${ADB_DEV_DIR}
			rm -rf $USB_DEV_FFS
		fi
		echo "OK"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
