######################################################################
# Automatically generated by qmake (1.07a) Sun Nov 2 12:33:31 2014
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += fbdevice.h jpegdecoder.h painter.h
SOURCES += fbdevice.c jpegdecoder.c main.c painter.c
