set(CPACK_GENERATOR "RPM")
set(CPACK_RPM_PACKAGE_MAINTAINER "Winddoing")
set(CPACK_RPM_PACKAGE_DESCRIPTION "This is a demo package from Winddoing.")
set(CPACK_RPM_PACKAGE_VERSION ${PACKAGE_VERSION})
set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
set(CPACK_RPM_PACKAGE_DEPENDS "libc6 (>= 2.3.1-6), libc6 (<< 3)")

