######################################################################
# Automatically generated by qmake (1.07a) Sat Nov 22 11:37:24 2014
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mymysql.h wave.h wavedata.h
SOURCES += main.c mymysql.c wave.c wavedata.c
