#ifndef _DW_MSHC_REGS_H_
#define _DW_MSHC_REGS_H_

#include <linux/bitops.h>

/**
 * MSHC Register Offset
 */
#define MSHC_SDMASA_R						(0x0)
#define MSHC_BLOCKSIZE_R					(0x4)
#define MSHC_BLOCKCOUNT_R					(0x6)
#define MSHC_ARGUMENT_R						(0x8)
#define MSHC_XFER_MODE_R					(0xc)
#define MSHC_CMD_R							(0xe)
#define MSHC_RESP01_R						(0x10)
#define MSHC_RESP23_R						(0x14)
#define MSHC_RESP45_R						(0x18)
#define MSHC_RESP67_R						(0x1c)
#define MSHC_BUF_DATA_R						(0x20)
#define MSHC_PSTATE_REG						(0x24)
#define MSHC_HOST_CTRL1_R					(0x28)
#define MSHC_PWR_CTRL_R						(0x29)
#define MSHC_BGAP_CTRL_R					(0x2a)
#define MSHC_WUP_CTRL_R						(0x2b)
#define MSHC_CLK_CTRL_R						(0x2c)
#define MSHC_TOUT_CTRL_R					(0x2e)
#define MSHC_SW_RST_R						(0x2f)
#define MSHC_NORMAL_INT_STAT_R				(0x30)
#define MSHC_ERROR_INT_STAT_R				(0x32)
#define MSHC_NORMAL_INT_STAT_EN_R			(0x34)
#define MSHC_ERROR_INT_STAT_EN_R			(0x36)
#define MSHC_NORMAL_INT_SIGNAL_EN_R			(0x38)
#define MSHC_ERROR_INT_SIGNAL_EN_R			(0x3a)
#define MSHC_AUTO_CMD_STAT_R				(0x3c)
#define MSHC_HOST_CTRL2_R					(0x3e)
#define MSHC_CAPABILITIES1_R				(0x40)
#define MSHC_CAPABILITIES2_R				(0x44)
#define MSHC_CURR_CAPABILITIES1_R			(0x48)
#define MSHC_CURR_CAPABILITIES2_R			(0x4c)
#define MSHC_FORCE_AUTO_CMD_STAT_R			(0x50)
#define MSHC_FORCE_ERROR_INT_STAT_R			(0x52)
#define MSHC_ADMA_ERR_STAT_R				(0x54)
#define MSHC_ADMA_SA_LOW_R					(0x58)
#define MSHC_ADMA_SA_HIGH_R					(0x5c)
#define MSHC_PRESET_INIT_R					(0x60)
#define MSHC_PRESET_DS_R					(0x62)
#define MSHC_PRESET_HS_R					(0x64)
#define MSHC_PRESET_SDR12_R					(0x66)
#define MSHC_PRESET_SDR25_R					(0x68)
#define MSHC_PRESET_SDR50_R					(0x6a)
#define MSHC_PRESET_SDR104_R				(0x6c)
#define MSHC_PRESET_DDR50_R					(0x6e)
#define MSHC_ADMA_ID_LOW_R					(0x78)
#define MSHC_ADMA_ID_HIGH_R					(0x7c)
#define MSHC_P_EMBEDDED_CNTRL				(0xe6)
#define MSHC_P_VENDOR_SPECIFIC_AREA			(0xe8)
#define MSHC_P_VENDOR2_SPECIFIC_AREA		(0xea)
#define MSHC_SLOT_INTR_STATUS_R				(0xfc)
#define MSHC_HOST_CNTRL_VERS_R				(0xfe)

#define MSHC_EMBEDDED_CTRL_R				(0x0)

#define MSHC_CQVER							(0x0)
#define MSHC_CQCAP							(0x4)
#define MSHC_CQCFG							(0x8)
#define MSHC_CQIS							(0x10)
#define MSHC_CQISE							(0x14)
#define MSHC_CQISGE							(0x18)
#define MSHC_CQIC							(0x1c)
#define MSHC_CQTDLBA						(0x20)
#define MSHC_CQTDBR							(0x28)
#define MSHC_CQTCN							(0x2c)
#define MSHC_CQDQS							(0x30)
#define MSHC_CQDPT							(0x34)
#define	MSHC_CQTCLR							(0x38)
#define MSHC_CQSSC1							(0x40)
#define MSHC_CQSSC2							(0x44)
#define MSHC_CQCRDCT						(0x48)
#define MSHC_CQRMEM							(0x50)
#define MSHC_CQTERRI						(0x54)
#define MSHC_CQCRI							(0x58)
#define MSHC_CQCRA							(0x5c)

#define MSHC_VER_ID_R						(0x0)
#define MSHC_VER_TYPE_R						(0x4)
#define MSHC_EMMC_CTRL_R					(0x2c)
#define MSHC_BOOT_CTRL_R					(0x2e)
#define MSHC_GP_IN_R						(0x30)
#define MSHC_GP_OUT_R						(0x34)

/**
 * MSHC Register Bit Field Define
 */

/* BLOCKSIZE_R */
#define MSHC_SDMA_BUF_BDARY_HBIT			(14)
#define MSHC_SDMA_BUF_BDARY_LBIT			(12)
#define MSHC_SDMA_BUF_BDARY_MASK			GENMASK(MSHC_SDMA_BUF_BDARY_HBIT, MSHC_SDMA_BUF_BDARY_LBIT)
#define MSHC_SDMA_BUF_BDARY_BYTES_4K		(0x0 << MSHC_SDMA_BUF_BDARY_LBIT)
#define MSHC_SDMA_BUF_BDARY_BYTES_8K		(0x1 << MSHC_SDMA_BUF_BDARY_LBIT)
#define MSHC_SDMA_BUF_BDARY_BYTES_16K		(0x2 << MSHC_SDMA_BUF_BDARY_LBIT)
#define MSHC_SDMA_BUF_BDARY_BYTES_32K		(0x3 << MSHC_SDMA_BUF_BDARY_LBIT)
#define MSHC_SDMA_BUF_BDARY_BYTES_64K		(0x4 << MSHC_SDMA_BUF_BDARY_LBIT)
#define MSHC_SDMA_BUF_BDARY_BYTES_128K		(0x5 << MSHC_SDMA_BUF_BDARY_LBIT)
#define MSHC_SDMA_BUF_BDARY_BYTES_256K		(0x6 << MSHC_SDMA_BUF_BDARY_LBIT)
#define MSHC_SDMA_BUF_BDARY_BYTES_512K		(0x7 << MSHC_SDMA_BUF_BDARY_LBIT)

#define MSHC_XFER_BLOCK_SIZE_HBIT			(11)
#define MSHC_XFER_BLOCK_SIZE_LBIT			(0)
#define MSHC_XFER_BLOCK_SIZE_MASK			GENMASK(MSHC_XFER_BLOCK_SIZE_HBIT, MSHC_XFER_BLOCK_SIZE_LBIT)

/* XFER_MODE_R */
#define MSHC_RESP_INT_DISABLE_BIT			BIT(8)
#define MSHC_RESP_INT_ENABLE				(0)
#define MSHC_RESP_INT_DISABLE				(1)

#define MSHC_RESP_ERR_CHK_ENABLE_BIT		BIT(7)
#define MSHC_RESP_ERR_CHK_ENABLE			(0)
#define MSHC_RESP_ERR_CHK_DISABLE			(1)

#define MSHC_RESP_TYPE_BIT					BIT(6)
#define MSHC_RESP_TYPE_R1					(0)
#define MSHC_RESP_TYPE_R5					(1)

#define MSHC_MULTI_BLK_SEL_BIT				BIT(5)
#define MSHC_MULTI_BLK_SEL_SINGLE			(0)
#define MSHC_MULTI_BLK_SEL_MULTI			(1)

#define MSHC_DATA_XFER_DIR_BIT				BIT(4)
#define MSHC_DATA_XFER_DIR_WR				(0)
#define MSHC_DATA_XFER_DIR_RD				(1)

#define MSHC_AUTO_CMD_ENABLE_HBIT			(3)
#define MSHC_AUTO_CMD_ENABLE_LBIT			(2)
#define MSHC_AUTO_CMD_ENABLE_MASK			GENMASK(MSHC_AUTO_CMD_ENABLE_HBIT, MSHC_AUTO_CMD_ENABLE_LBIT)
#define MSHC_AUTO_CMD_DISABLE				(0x0 << MSHC_AUTO_CMD_ENABLE_LBIT)
#define MSHC_AUTO_CMD12_ENABLE				(0x1 << MSHC_AUTO_CMD_ENABLE_LBIT)
#define MSHC_AUTO_CMD23_ENABLE				(0x2 << MSHC_AUTO_CMD_ENABLE_LBIT)
#define MSHC_AUTO_CMD_AUTO_SEL				(0x3 << MSHC_AUTO_CMD_ENABLE_LBIT)

#define MSHC_BLOCK_COUNT_ENABLE_BIT			BIT(1)
#define MSHC_BLOCK_COUNT_DISABLE			(0)
#define MSHC_BLOCK_COUNT_ENABLE				(1)

#define MSHC_DMA_ENABLE_BIT					BIT(0)
#define MSHC_DMA_DISABLE					(0)
#define MSHC_DMA_ENABLE						(1)

/* CMD_R */
#define MSHC_CMD_INDEX_HBIT					(13)
#define MSHC_CMD_INDEX_LBIT					(8)
#define MSHC_CMD_INDEX_MASK					GENMASK(MSHC_CMD_INDEX_HBIT, MSHC_CMD_INDEX_LBIT)

#define MSHC_CMD_TYPE_HBIT					(7)
#define MSHC_CMD_TYPE_LBIT					(6)
#define MSHC_CMD_TYPE_MASK					GENMASK(MSHC_CMD_INDEX_HBIT, MSHC_CMD_INDEX_LBIT)
#define	MSHC_CMD_TYPE_NORMAL_CMD			(0x0 << MSHC_CMD_TYPE_LBIT)
#define MSHC_CMD_TYPE_SUSPEND_CMD			(0x1 << MSHC_CMD_TYPE_LBIT)
#define MSHC_CMD_TYPE_RESUME_CMD			(0x2 << MSHC_CMD_TYPE_LBIT)
#define MSHC_CMD_TYPE_ABORT_CMD				(0x3 << MSHC_CMD_TYPE_LBIT)

#define MSHC_DATA_PRESENT_SEL_BIT			BIT(5)
#define MSHC_DATA_PRESENT_SEL_NO_DATA		(0)
#define MSHC_DATA_PRESENT_SEL_DATA			(1)

#define MSHC_CMD_IDX_CHK_ENABLE_BIT			BIT(4)
#define MSHC_CMD_IDX_CHK_DISABLE			(0)
#define MSHC_CMD_IDX_CHK_ENABLE				(1)

#define MSHC_CMD_CRC_CHK_ENABLE_BIT			BIT(3)
#define MSHC_CMD_CRC_CHK_DISABLE			(0)
#define MSHC_CMD_CRC_CHK_ENABLE				(1)

#define MSHC_SUB_CMD_FLAG_BIT				BIT(2)
#define MSHC_SUB_CMD_FLAG_MAIN				(0)
#define MSHC_SUB_CMD_FLAG_SUB				(1)

#define MSHC_RESP_TYPE_SELECT_HBIT			(1)
#define MSHC_RESP_TYPE_SELECT_LBIT			(0)
#define MSHC_RESP_TYPE_SELECT_MASK			GENMASK(MSHC_RESP_TYPE_SELECT_HBIT, MSHC_RESP_TYPE_SELECT_LBIT)
#define MSHC_RESP_TYPE_SELECT_NO_RESP		(0x0 << MSHC_RESP_TYPE_SELECT_LBIT)
#define MSHC_RESP_TYPE_SELECT_RESP_LEN_136	(0x1 << MSHC_RESP_TYPE_SELECT_LBIT)
#define MSHC_RESP_TYPE_SELECT_RESP_LEN_48	(0x2 << MSHC_RESP_TYPE_SELECT_LBIT)
#define MSHC_RESP_TYPE_SELECT_RESP_LEN_48B	(0x3 << MSHC_RESP_TYPE_SELECT_LBIT)

/* PSTATE_REG */
#define MSHC_UHS2_IF_DETECT_BIT				BIT(31)
#define MSHC_UHS2_IF_DETECT_FALSE			(0)
#define MSHC_UHS2_IF_DETECT_TRUE			(1)

#define MSHC_LANE_SYNC_BIT					BIT(30)
#define MSHC_LANE_SYNC_FALSE				(0)
#define MSHC_LANE_SYNC_TRUE					(1)

#define MSHC_IN_DORMANT_ST_BIT				BIT(29)
#define MSHC_IN_DORMANT_ST_FALSE			(0)
#define MSHC_IN_DORMANT_ST_TRUE				(1)

#define MSHC_SUB_CMD_STAT_BIT				BIT(28)
#define MSHC_SUB_CMD_STAT_FALSE				(0)
#define MSHC_SUB_CMD_STAT_TRUE				(1)

#define MSHC_CMD_ISSUE_ERR_BIT				BIT(27)
#define MSHC_CMD_ISSUE_ERR_FALSE			(0)
#define MSHC_CMD_ISSUE_ERR_TRUE				(1)

#define MSHC_HOST_REG_VOL_BIT				BIT(25)
#define MSHC_HOST_REG_VOL_FALSE				(0)
#define MSHC_HOST_REG_VOL_TRUE				(1)

#define MSHC_CMD_LINE_LVL_BIT				BIT(24)

#define MSHC_DAT_3_0_HBIT					(23)
#define MSHC_DAT_3_0_LBIT					(20)
#define MSHC_DAT_3_0_MASK					GENMASK(MSHC_DAT_3_0_HBIT, MSHC_DAT_3_0_LBIT)

#define MSHC_WR_PROTECT_SW_LVL_BIT			BIT(19)
#define MSHC_WR_PROTECT_SW_LVL_FALSE		(0)
#define MSHC_WR_PROTECT_SW_LVL_TRUE			(1)

#define MSHC_CARD_DETECT_PIN_LEVEL_BIT		BIT(18)
#define MSHC_CARD_DETECT_PIN_LEVEL_FALSE	(0)
#define MSHC_CARD_DETECT_PIN_LEVEL_TRUE		(1)

#define MSHC_CARD_STABLE_BIT				BIT(17)
#define MSHC_CARD_STABLE_FALSE				(0)
#define MSHC_CARD_STABLE_TRUE				(1)

#define MSHC_CARD_INSERTED_BIT				BIT(16)
#define MSHC_CARD_INSERTED_FALSE			(0)
#define MSHC_CARD_INSERTED_TRUE				(1)

#define MSHC_BUF_RD_ENABLE_BIT				BIT(11)
#define MSHC_BUF_RD_DISABLE					(0)
#define MSHC_BUF_RD_ENABLE					(1)

#define MSHC_BUF_WR_ENABLE_BIT				BIT(10)
#define MSHC_BUF_WR_DISABLE					(0)
#define MSHC_BUF_WR_ENABLE					(1)

#define MSHC_RD_XFER_ACTIVE_BIT				BIT(9)
#define MSHC_RD_XFER_INACTIVE				(0)
#define MSHC_RD_XFER_ACTIVE					(1)

#define MSHC_WR_XFER_ACTIVE_BIT				BIT(8)
#define MSHC_WR_XFER_INACTIVE				(0)
#define MSHC_WR_XFER_ACTIVE					(1)

#define MSHC_DAT_7_4_HBIT					(7)
#define MSHC_DAT_7_4_LBIT					(4)
#define MSHC_DAT_7_4_MASK					GENMASK(MSHC_DAT_7_4_HBIT, MSHC_DAT_7_4_LBIT)

#define MSHC_RE_TUNE_REQ_BIT				BIT(3)
#define MSHC_RE_TUNE_REQ_FIXED				(0)
#define MSHC_RE_TUNE_REQ_RE_TUNE			(1)

#define MSHC_DAT_LINE_ACTIVE_BIT			BIT(2)
#define MSHC_DAT_LINE_INACTIVE				(0)
#define MSHC_DAT_LINE_ACTIVE				(1)

#define MSHC_CMD_INHIBIT_DAT_BIT			BIT(1)
#define MSHC_CMD_INHIBIT_DAT_READY			(0)
#define MSHC_CMD_INHIBIT_DAT_NOT_READY		(1)

#define MSHC_CMD_INHIBIT_BIT				BIT(0)
#define MSHC_CMD_INHIBIT_READY				(0)
#define MSHC_CMD_INHIBIT_NOT_READY			(1)

/* HOST_CTRL1_R */
#define MSHC_CARD_DETECT_SIG_LVL_BIT		BIT(7)
#define MSHC_CARD_DETECT_SIG_LVL_SDCD_PIN	(0)
#define MSHC_CARD_DETECT_SIG_LVL_TEST_LEVEL	(1)

#define MSHC_CARD_DETECT_TEST_LVL_BIT		BIT(6)
#define MSHC_CARD_DETECT_TEST_LVL_NO_CARD	(0)
#define MSHC_CARD_DETECT_TEST_LVL_INSERTED	(1)

#define MSHC_EXT_DAT_XFER_BIT				BIT(5)
#define MSHC_EXT_DAT_XFER_DEFAULT			(0)
#define MSHC_EXT_DAT_XFER_EIGHT_BIT			(1)

#define MSHC_DMA_SEL_HBIT					(4)
#define MSHC_DMA_SEL_LBIT					(3)
#define MSHC_DMA_SEL_MASK					GENMASK(MSHC_DMA_SEL_HBIT, MSHC_DMA_SEL_LBIT)
#define MSHC_DMA_SEL_SDMA					(0x0 << MSHC_DMA_SEL_LBIT)
#define MSHC_DMA_SEL_RSVD_BIT				(0x1 << MSHC_DMA_SEL_LBIT)
#define MSHC_DMA_SEL_ADMA2					(0x2 << MSHC_DMA_SEL_LBIT)
#define MSHC_DMA_SEL_ADMA2_3				(0x3 << MSHC_DMA_SEL_LBIT)

#define MSHC_HIGH_SPEED_EN_BIT				BIT(2)
#define MSHC_HIGH_SPEED_EN_NORMAL			(0)
#define MSHC_HIGH_SPEED_EN_HIGH				(1)

#define MSHC_DAT_XFER_WIDTH_BIT				BIT(1)
#define MSHC_DAT_XFER_WIDTH_BITS_1			(0)
#define MSHC_DAT_XFER_WIDTH_BITS_4			(1)

#define MSHC_LED_CTRL_BIT					BIT(0)
#define MSHC_LED_CTRL_OFF					(0)
#define MSHC_LED_CTRL_ON					(1)

/* PWR_CTRL_R */
#define MSHC_SD_BUS_VOL_VDD2_HBIT			(7)
#define MSHC_SD_BUS_VOL_VDD2_LBIT			(5)
#define MSHC_SD_BUS_VOL_VDD2_MASK			GENMASK(MSHC_SD_BUS_VOL_VDD2_HBIT, MSHC_SD_BUS_VOL_VDD2_LBIT)
#define MSHC_SD_BUS_VOL_VDD2_NO_VDD2		(0x0 << MSHC_SD_BUS_VOL_VDD2_LBIT)
#define MSHC_SD_BUS_VOL_VDD2_RSVD1			(0x1 << MSHC_SD_BUS_VOL_VDD2_LBIT)
#define MSHC_SD_BUS_VOL_VDD2_RSVD2			(0x2 << MSHC_SD_BUS_VOL_VDD2_LBIT)
#define MSHC_SD_BUS_VOL_VDD2_RSVD3			(0x3 << MSHC_SD_BUS_VOL_VDD2_LBIT)
#define MSHC_SD_BUS_VOL_VDD2_V_1_2			(0x4 << MSHC_SD_BUS_VOL_VDD2_LBIT)
#define MSHC_SD_BUS_VOL_VDD2_V_1_8			(0x5 << MSHC_SD_BUS_VOL_VDD2_LBIT)
#define MSHC_SD_BUS_VOL_VDD2_NOT_USED6		(0x6 << MSHC_SD_BUS_VOL_VDD2_LBIT)
#define MSHC_SD_BUS_VOL_VDD2_NOT_USED7		(0x7 << MSHC_SD_BUS_VOL_VDD2_LBIT)

#define MSHC_SD_BUS_PWR_VDD2_BIT			BIT(4)
#define MSHC_SD_BUS_PWR_VDD2_OFF			(0)
#define MSHC_SD_BUS_PWR_VDD2_ON				(1)

#define MSHC_SD_BUS_VOL_VDD1_HBIT			(3)
#define MSHC_SD_BUS_VOL_VDD1_LBIT			(1)
#define MSHC_SD_BUS_VOL_VDD1_MASK			GENMASK(MSHC_SD_BUS_VOL_VDD1_HBIT, MSHC_SD_BUS_VOL_VDD1_LBIT)
#define MSHC_SD_BUS_VOL_VDD1_RSVD0			(0x0 << MSHC_SD_BUS_VOL_VDD1_LBIT)
#define MSHC_SD_BUS_VOL_VDD1_RSVD1			(0x1 << MSHC_SD_BUS_VOL_VDD1_LBIT)
#define MSHC_SD_BUS_VOL_VDD1_RSVD2			(0x2 << MSHC_SD_BUS_VOL_VDD1_LBIT)
#define MSHC_SD_BUS_VOL_VDD1_RSVD3			(0x3 << MSHC_SD_BUS_VOL_VDD1_LBIT)
#define MSHC_SD_BUS_VOL_VDD1_RSVD4			(0x4 << MSHC_SD_BUS_VOL_VDD1_LBIT)
#define MSHC_SD_BUS_VOL_VDD1_V_1_8			(0x5 << MSHC_SD_BUS_VOL_VDD1_LBIT)
#define MSHC_SD_BUS_VOL_VDD1_V_3_0			(0x6 << MSHC_SD_BUS_VOL_VDD1_LBIT)
#define MSHC_SD_BUS_VOL_VDD1_V_3_3			(0x7 << MSHC_SD_BUS_VOL_VDD1_LBIT)

#define MSHC_SD_BUS_PWR_VDD1_BIT			BIT(0)
#define MSHC_SD_BUS_PWR_VDD1_OFF			(0)
#define MSHC_SD_BUS_PWR_VDD1_ON				(1)

/* BGAP_CTRL_R */
#define MSHC_INT_AT_BGAP_BIT				BIT(3)
#define MSHC_INT_AT_BGAP_DISABLE			(0)
#define MSHC_INT_AT_BGAP_ENABLE				(1)

#define MSHC_RD_WAIT_CTRL_BIT				BIT(2)
#define MSHC_RD_WAIT_CTRL_DISABLE			(0)
#define MSHC_RD_WAIT_CTRL_ENABLE			(1)

#define MSHC_CONTINUE_REQ_BIT				BIT(1)
#define MSHC_CONTINUE_REQ_NOT_AFFECT		(0)
#define MSHC_CONTINUE_REQ_NOT_RESTART		(1)

#define MSHC_STOP_BG_REQ_BIT				BIT(0)
#define MSHC_STOP_BG_REQ_XFER				(0)
#define MSHC_STOP_BG_REQ_STOP				(1)

/* WUP_CTRL_R */
#define MSHC_CARD_REMOVAL_BIT				BIT(2)
#define MSHC_CARD_REMOVAL_DISABLE			(0)
#define MSHC_CARD_REMOVAL_ENABLE			(1)

#define MSHC_CARD_INSERT_BIT				BIT(1)
#define MSHC_CARD_INSERT_DISABLE			(0)
#define MSHC_CARD_INSERT_ENABLE				(1)

#define MSHC_CARD_INT_BIT					BIT(0)
#define MSHC_CARD_INT_DISABLE				(0)
#define MSHC_CARD_INT_ENABLE				(1)

/* CLK_CTRL_R */
#define MSHC_FREQ_SEL_HBIT					(15)
#define MSHC_FREQ_SEL_LBIT					(8)
#define MSHC_FREQ_SEL_MASK					GENMASK(MSHC_FREQ_SEL_HBIT, MSHC_FREQ_SEL_LBIT)

#define MSHC_UPPER_FREQ_SEL_HBIT			(7)
#define MSHC_UPPER_FREQ_SEL_LBIT			(6)
#define MSHC_UPPER_FREQ_SEL_MASK			GENMASK(MSHC_UPPER_FREQ_SEL_HBIT, MSHC_UPPER_FREQ_SEL_LBIT)

#define MSHC_CLK_GEN_SELECT_BIT				BIT(5)
#define MSHC_CLK_GEN_SELECT_FALSE			(0)
#define MSHC_CLK_GEN_SELECT_TRUE			(1)

#define MSHC_PLL_ENABLE_BIT					BIT(3)
#define MSHC_PLL_ENABLE_FALSE				(0)
#define MSHC_PLL_ENABLE_TRUE				(1)

#define MSHC_SD_CLK_EN_BIT					BIT(2)
#define MSHC_SD_CLK_EN_FALSE				(0)
#define MSHC_SD_CLK_EN_TRUE					(1)

#define MSHC_INTERNAL_CLK_STABLE_BIT		BIT(1)
#define MSHC_INTERNAL_CLK_STABLE_FALSE		(0)
#define MSHC_INTERNAL_CLK_STABLE_TRUE		(1)

#define MSHC_INTERNAL_CLK_EN_BIT			BIT(0)
#define MSHC_INTERNAL_CLK_EN_FALSE			(0)
#define MSHC_INTERNAL_CLK_EN_TRUE			(1)

/* TOUT_CTRL_R */
#define MSHC_TOUT_CNT_HBIT					(3)
#define MSHC_TOUT_CNT_LBIT					(0)
#define MSHC_TOUT_CNT_MASK					GENMASK(MSHC_TOUT_CNT_HBIT, MSHC_TOUT_CNT_LBIT)

/* SW_RST_R */
#define MSHC_SW_RST_DAT_BIT					BIT(2)
#define	MSHC_SW_RST_DAT_FALSE				(0)
#define MSHC_SW_RST_DAT_TRUE				(1)

#define MSHC_SW_RST_CMD_BIT					BIT(1)
#define MSHC_SW_RST_CMD_FALSE				(0)
#define MSHC_SW_RST_CMD_TRUE				(1)

#define MSHC_SW_RST_ALL_BIT					BIT(0)
#define MSHC_SW_RST_ALL_FALSE				(0)
#define MSHC_SW_RST_ALL_TRUE				(1)

/* NORMAL_INT_STAT_R */
#define MSHC_ERR_INTERRUPT_STAT_BIT			BIT(15)
#define MSHC_ERR_INTERRUPT_STAT_FALSE		(0)
#define MSHC_ERR_INTERRUPT_STAT_TRUE		(1)

#define MSHC_CQE_EVENT_STAT_BIT				BIT(14)
#define MSHC_CQE_EVENT_STAT_FALSE			(0)
#define MSHC_CQE_EVENT_STAT_TRUE			(1)

#define MSHC_FX_EVENT_STAT_BIT				BIT(13)
#define MSHC_FX_EVENT_STAT_FALSE			(0)
#define MSHC_FX_EVENT_STAT_TRUE				(1)

#define MSHC_RE_TUNE_EVENT_STAT_BIT			BIT(12)
#define MSHC_RE_TUNE_EVENT_STAT_FALSE		(0)
#define MSHC_RE_TUNE_EVENT_STAT_TRUE		(1)

#define MSHC_INT_C_STAT_BIT					BIT(11)
#define MSHC_INT_C_STAT_FALSE				(0)
#define MSHC_INT_C_STAT_TRUE				(1)

#define MSHC_INT_B_STAT_BIT					BIT(10)
#define MSHC_INT_B_STAT_FALSE				(0)
#define MSHC_INT_B_STAT_TRUE				(1)

#define MSHC_INT_A_STAT_BIT					BIT(9)
#define MSHC_INT_A_STAT_FALSE				(0)
#define MSHC_INT_A_STAT_TRUE				(1)

#define MSHC_CARD_INTERRUPT_STAT_BIT		BIT(8)
#define MSHC_CARD_INTERRUPT_STAT_FALSE		(0)
#define MSHC_CARD_INTERRUPT_STAT_TRUE		(1)

#define MSHC_CARD_REMOVAL_STAT_BIT			BIT(7)
#define MSHC_CARD_REMOVAL_STAT_FALSE		(0)
#define MSHC_CARD_REMOVAL_STAT_TRUE			(1)

#define MSHC_CARD_INSERTION_STAT_BIT		BIT(6)
#define MSHC_CARD_INSERTION_STAT_FALSE		(0)
#define MSHC_CARD_INSERTION_STAT_TRUE		(1)

#define MSHC_BUF_RD_READY_STAT_BIT			BIT(5)
#define MSHC_BUF_RD_READY_STAT_FALSE		(0)
#define MSHC_BUF_RD_READY_STAT_TRUE			(1)

#define MSHC_BUF_WR_READY_STAT_BIT			BIT(4)
#define MSHC_BUF_WR_READY_STAT_FALSE		(0)
#define MSHC_BUF_WR_READY_STAT_TRUE			(1)

#define MSHC_DMA_INTERRUPT_STAT_BIT			BIT(3)
#define MSHC_DMA_INTERRUPT_STAT_FALSE		(0)
#define MSHC_DMA_INTERRUPT_STAT_TRUE		(1)

#define MSHC_BGAP_EVENT_STAT_BIT			BIT(2)
#define MSHC_BGAP_EVENT_STAT_FALSE			(0)
#define MSHC_BGAP_EVENT_STAT_TRUE			(1)

#define MSHC_XFER_COMPLETE_STAT_BIT			BIT(1)
#define MSHC_XFER_COMPLETE_STAT_FALSE		(0)
#define MSHC_XFER_COMPLETE_STAT_TRUE		(1)

#define MSHC_CMD_COMPLETE_STAT_BIT			BIT(0)
#define MSHC_CMD_COMPLETE_STAT_FALSE		(0)
#define MSHC_CMD_COMPLETE_STAT_TRUE			(1)

/* ERROR_INT_STAT_R */
#define MSHC_VENDOR_ERR3_STAT_BIT			BIT(15)
#define MSHC_VENDOR_ERR3_STAT_FALSE			(0)
#define MSHC_VENDOR_ERR3_STAT_TRUE			(1)

#define MSHC_VENDOR_ERR2_STAT_BIT			BIT(14)
#define MSHC_VENDOR_ERR2_STAT_FALSE			(0)
#define MSHC_VENDOR_ERR2_STAT_TRUE			(1)

#define MSHC_VENDOR_ERR1_STAT_BIT			BIT(13)
#define MSHC_VENDOR_ERR1_STAT_FALSE			(0)
#define MSHC_VENDOR_ERR1_STAT_TRUE			(1)

#define MSHC_BOOT_ACK_ERR_STAT_BIT			BIT(12)
#define MSHC_BOOT_ACK_ERR_STAT_FALSE		(0)
#define MSHC_BOOT_ACK_ERR_STAT_TRUE			(1)

#define MSHC_RESP_ERR_STAT_BIT				BIT(11)
#define MSHC_RESP_ERR_STAT_FALSE			(0)
#define MSHC_RESP_ERR_STAT_TRUE				(1)

#define MSHC_TUNING_ERR_STAT_BIT			BIT(10)
#define MSHC_TUNING_ERR_STAT_FALSE			(0)
#define MSHC_TUNING_ERR_STAT_TRUE			(1)

#define MSHC_ADMA_ERR_STAT_BIT				BIT(9)
#define MSHC_ADMA_ERR_STAT_FALSE			(0)
#define MSHC_ADMA_ERR_STAT_TRUE				(1)

#define MSHC_AUTO_CMD_ERR_STAT_BIT			BIT(8)
#define MSHC_AUTO_CMD_ERR_STAT_FALSE		(0)
#define MSHC_AUTO_CMD_ERR_STAT_TRUE			(1)

#define MSHC_CUR_LMT_ERR_STAT_BIT			BIT(7)
#define MSHC_CUR_LMT_ERR_STAT_FALSE			(0)
#define MSHC_CUR_LMT_ERR_STAT_TRUE			(1)

#define MSHC_DATA_END_BIT_ERR_STAT_BIT		BIT(6)
#define MSHC_DATA_END_BIT_ERR_STAT_FALSE	(0)
#define MSHC_DATA_END_BIT_ERR_STAT_TRUE		(1)

#define MSHC_DATA_CRC_ERR_STAT_BIT			BIT(5)
#define MSHC_DATA_CRC_ERR_STAT_FALSE		(0)
#define MSHC_DATA_CRC_ERR_STAT_TRUE			(1)

#define MSHC_DATA_TOUT_ERR_STAT_BIT			BIT(4)
#define MSHC_DATA_TOUT_ERR_STAT_FALSE		(0)
#define MSHC_DATA_TOUT_ERR_STAT_TRUE		(1)

#define MSHC_CMD_IDX_ERR_STAT_BIT			BIT(3)
#define MSHC_CMD_IDX_ERR_STAT_FALSE			(0)
#define MSHC_CMD_IDX_ERR_STAT_TRUE			(1)

#define MSHC_CMD_END_BIT_ERR_STAT_BIT		BIT(2)
#define MSHC_CMD_END_BIT_ERR_STAT_FALSE		(0)
#define MSHC_CMD_END_BIT_ERR_STAT_TRUE		(1)

#define MSHC_CMD_CRC_ERR_STAT_BIT			BIT(1)
#define MSHC_CMD_CRC_ERR_STAT_FALSE			(0)
#define MSHC_CMD_CRC_ERR_STAT_TRUE			(1)

#define MSHC_CMD_TOUT_ERR_STAT_BIT			BIT(0)
#define MSHC_CMD_TOUT_ERR_STAT_FALSE		(0)
#define MSHC_CMD_TOUT_ERR_STAT_TRUE			(1)

/* NORMAL_INT_STAT_EN_R */
#define MSHC_CQE_EVENT_STAT_EN_BIT			BIT(14)
#define MSHC_CQE_EVENT_STAT_EN_FALSE		(0)
#define MSHC_CQE_EVENT_STAT_EN_TRUE			(1)

#define MSHC_FX_EVENT_STAT_EN_BIT			BIT(13)
#define MSHC_FX_EVENT_STAT_EN_FALSE			(0)
#define MSHC_FX_EVENT_STAT_EN_TRUE			(1)

#define MSHC_RE_TUNE_EVENT_STAT_EN_BIT		BIT(12)
#define MSHC_RE_TUNE_EVENT_STAT_EN_FALSE	(0)
#define MSHC_RE_TUNE_EVENT_STAT_EN_TRUE		(1)

#define MSHC_INT_C_EVENT_STAT_EN_BIT		BIT(11)
#define MSHC_INT_C_EVENT_STAT_EN_FALSE		(0)
#define MSHC_INT_C_EVENT_STAT_EN_TRUE		(1)

#define MSHC_INT_B_EVENT_STAT_EN_BIT		BIT(10)
#define MSHC_INT_B_EVENT_STAT_EN_FALSE		(0)
#define MSHC_INT_B_EVENT_STAT_EN_TRUE		(1)

#define MSHC_INT_A_EVENT_STAT_EN_BIT		BIT(9)
#define MSHC_INT_A_EVENT_STAT_EN_FALSE		(0)
#define MSHC_INT_A_EVENT_STAT_EN_TRUE		(1)

#define MSHC_CARD_INTERRUPT_STAT_EN_BIT		BIT(8)
#define MSHC_CARD_INTERRUPT_STAT_EN_FALSE	(0)
#define MSHC_CARD_INTERRUPT_STAT_EN_TRUE	(1)

#define MSHC_CARD_REMOVAL_STAT_EN_BIT		BIT(7)
#define MSHC_CARD_REMOVAL_STAT_EN_FALSE		(0)
#define MSHC_CARD_REMOVAL_STAT_EN_TRUE		(1)

#define MSHC_CARD_INSERTION_STAT_EN_BIT		BIT(6)
#define MSHC_CARD_INSERTION_STAT_EN_FALSE	(0)
#define MSHC_CARD_INSERTION_STAT_EN_TRUE	(1)

#define MSHC_BUF_RD_READY_STAT_EN_BIT		BIT(5)
#define MSHC_BUF_RD_READY_STAT_EN_FALSE		(0)
#define MSHC_BUF_RD_READY_STAT_EN_TRUE		(1)

#define MSHC_BUF_WR_READY_STAT_EN_BIT		BIT(4)
#define MSHC_BUF_WR_READY_STAT_EN_FALSE		(0)
#define MSHC_BUF_WR_READY_STAT_EN_TRUE		(1)

#define MSHC_DMA_INTERRUPT_STAT_EN_BIT		BIT(3)
#define MSHC_DMA_INTERRUPT_STAT_EN_FALSE	(0)
#define MSHC_DMA_INTERRUPT_STAT_EN_TRUE		(1)

#define MSHC_BGAP_EVENT_STAT_EN_BIT			BIT(2)
#define MSHC_BGAP_EVENT_STAT_EN_FALSE		(0)
#define MSHC_BGAP_EVENT_STAT_EN_TRUE		(1)

#define MSHC_XFER_COMPLETE_STAT_EN_BIT		BIT(1)
#define MSHC_XFER_COMPLETE_STAT_EN_FALSE	(0)
#define MSHC_XFER_COMPLETE_STAT_EN_TRUE		(1)

#define MSHC_CMD_COMPLETE_STAT_EN_BIT		BIT(0)
#define MSHC_CMD_COMPLETE_STAT_EN_FALSE		(0)
#define MSHC_CMD_COMPLETE_STAT_EN_TRUE		(1)

/* ERROR_INT_STAT_EN_R */
#define MSHC_VENDOR_ERR3_STAT_EN_BIT		BIT(15)
#define MSHC_VENDOR_ERR3_STAT_EN_FALSE		(0)
#define MSHC_VENDOR_ERR3_STAT_EN_TRUE		(1)

#define MSHC_VENDOR_ERR2_STAT_EN_BIT		BIT(14)
#define MSHC_VENDOR_ERR2_STAT_EN_FALSE		(0)
#define MSHC_VENDOR_ERR2_STAT_EN_TRUE		(1)

#define MSHC_VENDOR_ERR1_STAT_EN_BIT		BIT(13)
#define MSHC_VENDOR_ERR1_STAT_EN_FALSE		(0)
#define MSHC_VENDOR_ERR1_STAT_EN_TRUE		(1)

#define MSHC_BOOT_ACK_ERR_STAT_EN_BIT		BIT(12)
#define MSHC_BOOT_ACK_ERR_STAT_EN_FALSE		(0)
#define MSHC_BOOT_ACK_ERR_STAT_EN_TRUE		(1)

#define MSHC_RESP_ERR_STAT_EN_BIT			BIT(11)
#define MSHC_RESP_ERR_STAT_EN_FALSE			(0)
#define MSHC_RESP_ERR_STAT_EN_TRUE			(1)

#define MSHC_TUNING_ERR_STAT_EN_BIT			BIT(10)
#define MSHC_TUNING_ERR_STAT_EN_FALSE		(0)
#define MSHC_TUNING_ERR_STAT_EN_TRUE		(1)

#define MSHC_ADMA_ERR_STAT_EN_BIT			BIT(9)
#define MSHC_ADMA_ERR_STAT_EN_FALSE			(0)
#define MSHC_ADMA_ERR_STAT_EN_TRUE			(1)

#define MSHC_AUTO_CMD_ERR_STAT_EN_BIT		BIT(8)
#define MSHC_AUTO_CMD_ERR_STAT_EN_FALSE		(0)
#define MSHC_AUTO_CMD_ERR_STAT_EN_TRUE		(1)

#define MSHC_CUR_LMT_ERR_STAT_EN_BIT		BIT(7)
#define MSHC_CUR_LMT_ERR_STAT_EN_FALSE		(0)
#define MSHC_CUR_LMT_ERR_STAT_EN_TRUE		(1)

#define MSHC_DATA_END_BIT_ERR_STAT_EN_BIT	BIT(6)
#define MSHC_DATA_END_BIT_ERR_STAT_EN_FALSE	(0)
#define MSHC_DATA_END_BIT_ERR_STAT_EN_TRUE	(1)

#define MSHC_DATA_CRC_ERR_STAT_EN_BIT		BIT(5)
#define MSHC_DATA_CRC_ERR_STAT_EN_FALSE		(0)
#define MSHC_DATA_CRC_ERR_STAT_EN_TRUE		(1)

#define MSHC_DATA_TOUT_ERR_STAT_EN_BIT		BIT(4)
#define MSHC_DATA_TOUT_ERR_STAT_EN_FALSE	(0)
#define MSHC_DATA_TOUT_ERR_STAT_EN_TRUE		(1)

#define MSHC_CMD_IDX_ERR_STAT_EN_BIT		BIT(3)
#define MSHC_CMD_IDX_ERR_STAT_EN_FALSE		(0)
#define MSHC_CMD_IDX_ERR_STAT_EN_TRUE		(1)

#define MSHC_CMD_END_BIT_ERR_STAT_EN_BIT	BIT(2)
#define MSHC_CMD_END_BIT_ERR_STAT_EN_FALSE	(0)
#define MSHC_CMD_END_BIT_ERR_STAT_EN_TRUE 	(1)

#define MSHC_CMD_CRC_ERR_STAT_EN_BIT		BIT(1)
#define MSHC_CMD_CRC_ERR_STAT_EN_FALSE		(0)
#define MSHC_CMD_CRC_ERR_STAT_EN_TRUE		(1)

#define MSHC_CMD_TOUT_ERR_STAT_EN_BIT		BIT(0)
#define MSHC_CMD_TOUT_ERR_STAT_EN_FALSE		(0)
#define MSHC_CMD_TOUT_ERR_STAT_EN_TRUE		(1)

/* NORMAL_INT_SIGNAL_EN_R */
#define MSHC_CQE_EVENT_SIGNAL_EN_BIT		BIT(14)
#define MSHC_CQE_EVENT_SIGNAL_EN_FALSE		(0)
#define MSHC_CQE_EVENT_SIGNAL_EN_TRUE		(1)

#define MSHC_FX_EVENT_SIGNAL_EN_BIT			BIT(13)
#define MSHC_FX_EVENT_SIGNAL_EN_FALSE		(0)
#define MSHC_FX_EVENT_SIGNAL_EN_TRUE		(1)

#define MSHC_RE_TUNE_EVENT_SIGNAL_EN_BIT	BIT(12)
#define MSHC_RE_TUNE_EVENT_SIGNAL_EN_FALSE	(0)
#define MSHC_RE_TUNE_EVENT_SIGNAL_EN_TRUE	(1)

#define MSHC_INT_C_EVENT_SIGNAL_EN_BIT		BIT(11)
#define MSHC_INT_C_EVENT_SIGNAL_EN_FALSE	(0)
#define MSHC_INT_C_EVENT_SIGNAL_EN_TRUE		(1)

#define MSHC_INT_B_EVENT_SIGNAL_EN_BIT		BIT(10)
#define MSHC_INT_B_EVENT_SIGNAL_EN_FALSE	(0)
#define MSHC_INT_B_EVENT_SIGNAL_EN_TRUE		(1)

#define MSHC_INT_A_EVENT_SIGNAL_EN_BIT		BIT(9)
#define MSHC_INT_A_EVENT_SIGNAL_EN_FALSE	(0)
#define MSHC_INT_A_EVENT_SIGNAL_EN_TRUE		(1)

#define MSHC_CARD_INTERRUPT_SIGNAL_EN_BIT	BIT(8)
#define MSHC_CARD_INTERRUPT_SIGNAL_EN_FALSE	(0)
#define MSHC_CARD_INTERRUPT_SIGNAL_EN_TRUE	(1)

#define MSHC_CARD_REMOVAL_SIGNAL_EN_BIT		BIT(7)
#define MSHC_CARD_REMOVAL_SIGNAL_EN_FALSE	(0)
#define MSHC_CARD_REMOVAL_SIGNAL_EN_TRUE	(1)

#define MSHC_CARD_INSERTION_SIGNAL_EN_BIT	BIT(6)
#define MSHC_CARD_INSERTION_SIGNAL_EN_FALSE	(0)
#define MSHC_CARD_INSERTION_SIGNAL_EN_TRUE	(1)

#define MSHC_BUF_RD_READY_SIGNAL_EN_BIT		BIT(5)
#define MSHC_BUF_RD_READY_SIGNAL_EN_FALSE	(0)
#define MSHC_BUF_RD_READY_SIGNAL_EN_TRUE	(1)

#define MSHC_BUF_WR_READY_SIGNAL_EN_BIT		BIT(4)
#define MSHC_BUF_WR_READY_SIGNAL_EN_FALSE	(0)
#define MSHC_BUF_WR_READY_SIGNAL_EN_TRUE	(1)

#define MSHC_DMA_INTERRUPT_SIGANL_EN_BIT	BIT(3)
#define MSHC_DMA_INTERRUPT_SIGANL_EN_FALSE	(0)
#define MSHC_DMA_INTERRUPT_SIGANL_EN_TRUE	(1)

#define MSHC_BGAP_EVENT_SIGNAL_EN_BIT		BIT(2)
#define MSHC_BGAP_EVENT_SIGNAL_EN_FALSE		(0)
#define MSHC_BGAP_EVENT_SIGNAL_EN_TRUE		(1)

#define MSHC_XFER_COMPLETE_SIGNAL_EN_BIT	BIT(1)
#define MSHC_XFER_COMPLETE_SIGNAL_EN_FALSE	(0)
#define MSHC_XFER_COMPLETE_SIGNAL_EN_TRUE	(1)

#define MSHC_CMD_COMPLETE_SIGNAL_EN_BIT		BIT(0)
#define MSHC_CMD_COMPLETE_SIGNAL_EN_FALSE	(0)
#define MSHC_CMD_COMPLETE_SIGNAL_EN_TRUE	(1)

/* ERROR_INT_SIGNAL_EN_R */
#define MSHC_VENDOR_ERR3_SIGNAL_EN_BIT		BIT(15)
#define MSHC_VENDOR_ERR3_SIGNAL_EN_FALSE	(0)
#define MSHC_VENDOR_ERR3_SIGNAL_EN_TRUE		(1)

#define MSHC_VENDOR_ERR2_SIGNAL_EN_BIT		BIT(14)
#define MSHC_VENDOR_ERR2_SIGNAL_EN_FALSE	(0)
#define MSHC_VENDOR_ERR2_SIGNAL_EN_TRUE		(1)

#define MSHC_VENDOR_ERR1_SIGNAL_EN_BIT		BIT(13)
#define MSHC_VENDOR_ERR1_SIGNAL_EN_FALSE	(0)
#define MSHC_VENDOR_ERR1_SIGNAL_EN_TRUE		(1)

#define MSHC_BOOT_ACK_ERR_SIGNAL_EN_BIT		BIT(12)
#define MSHC_BOOT_ACK_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_BOOT_ACK_ERR_SIGNAL_EN_TRUE	(1)

#define MSHC_RESP_ERR_SIGNAL_EN_BIT			BIT(11)
#define MSHC_RESP_ERR_SIGNAL_EN_FALSE		(0)
#define MSHC_RESP_ERR_SIGNAL_EN_TRUE		(1)

#define MSHC_TUNING_ERR_SIGNAL_EN_BIT		BIT(10)
#define MSHC_TUNING_ERR_SIGNAL_EN_FALSE		(0)
#define MSHC_TUNING_ERR_SIGNAL_EN_TRUE		(1)

#define MSHC_ADMA_ERR_SIGNAL_EN_BIT			BIT(9)
#define MSHC_ADMA_ERR_SIGNAL_EN_FALSE		(0)
#define MSHC_ADMA_ERR_SIGNAL_EN_TRUE		(1)

#define MSHC_AUTO_CMD_ERR_SIGNAL_EN_BIT		BIT(8)
#define MSHC_AUTO_CMD_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_AUTO_CMD_ERR_SIGNAL_EN_TRUE	(1)

#define MSHC_CUR_LMT_ERR_SIGNAL_EN_BIT		BIT(7)
#define MSHC_CUR_LMT_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_CUR_LMT_ERR_SIGNAL_EN_TRUE		(1)

#define MSHC_DATA_END_BIT_ERR_SIGNAL_EN_BIT		BIT(6)
#define MSHC_DATA_END_BIT_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_DATA_END_BIT_ERR_SIGNAL_EN_TRUE	(1)

#define MSHC_DATA_CRC_ERR_SIGNAL_EN_BIT		BIT(5)
#define MSHC_DATA_CRC_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_DATA_CRC_ERR_SIGNAL_EN_TRUE	(1)

#define MSHC_DATA_TOUT_ERR_SIGNAL_EN_BIT	BIT(4)
#define MSHC_DATA_TOUT_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_DATA_TOUT_ERR_SIGNAL_EN_TRUE	(1)

#define MSHC_CMD_IDX_ERR_SIGNAL_EN_BIT		BIT(3)
#define MSHC_CMD_IDX_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_CMD_IDX_ERR_SIGNAL_EN_TRUE		(1)

#define MSHC_CMD_END_BIT_ERR_SIGNAL_EN_BIT		BIT(2)
#define MSHC_CMD_END_BIT_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_CMD_END_BIT_ERR_SIGNAL_EN_TRUE 	(1)

#define MSHC_CMD_CRC_ERR_SIGNAL_EN_BIT		BIT(1)
#define MSHC_CMD_CRC_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_CMD_CRC_ERR_SIGNAL_EN_TRUE		(1)

#define MSHC_CMD_TOUT_ERR_SIGNAL_EN_BIT		BIT(0)
#define MSHC_CMD_TOUT_ERR_SIGNAL_EN_FALSE	(0)
#define MSHC_CMD_TOUT_ERR_SIGNAL_EN_TRUE	(1)

/* AUTO_CMD_STAT_R */
#define MSHC_CMD_NOT_ISSUED_AUTO_CMD12_BIT		BIT(7)
#define MSHC_CMD_NOT_ISSUED_AUTO_CMD12_FALSE	(0)
#define MSHC_CMD_NOT_ISSUED_AUTO_CMD12_TRUE		(1)

#define MSHC_AUTO_CMD_RESP_ERR_BIT			BIT(5)
#define MSHC_AUTO_CMD_RESP_ERR_FALSE		(0)
#define MSHC_AUTO_CMD_RESP_ERR_TRUE			(1)

#define MSHC_AUTO_CMD_IDX_ERR_BIT			BIT(4)
#define MSHC_AUTO_CMD_IDX_ERR_FALSE			(0)
#define MSHC_AUTO_CMD_IDX_ERR_TRUE			(1)

#define MSHC_AUTO_CMD_EBIT_ERR_BIT			BIT(3)
#define MSHC_AUTO_CMD_EBIT_ERR_FALSE		(0)
#define MSHC_AUTO_CMD_EBIT_ERR_TRUE			(1)

#define MSHC_AUTO_CMD_CRC_ERR_BIT			BIT(2)
#define MSHC_AUTO_CMD_CRC_ERR_FALSE			(0)
#define MSHC_AUTO_CMD_CRC_ERR_TRUE			(1)

#define MSHC_AUTO_CMD_TOUT_ERR_BIT			BIT(1)
#define MSHC_AUTO_CMD_TOUT_ERR_FALSE		(0)
#define MSHC_AUTO_CMD_TOUT_ERR_TRUE			(1)

#define MSHC_AUTO_CMD12_NOT_EXEC_BIT		BIT(0)
#define MSHC_AUTO_CMD12_NOT_EXEC_FALSE		(0)
#define MSHC_AUTO_CMD12_NOT_EXEC_TRUE		(1)

/* HOST_CTRL2_R */
#define MSHC_PRESET_VAL_ENABLE_BIT			BIT(15)
#define MSHC_PRESET_VAL_ENABLE_FALSE		(0)
#define MSHC_PRESET_VAL_ENABLE_TRUE			(1)

#define MSHC_ASYNC_INT_ENABLE_BIT			BIT(14)
#define MSHC_ASYNC_INT_ENABLE_FALSE			(0)
#define MSHC_ASYNC_INT_ENABLE_TRUE			(1)

#define MSHC_ADDRESSING_BIT					BIT(13)
#define MSHC_ADDRESSING_32				(0)
#define MSHC_ADDRESSING_64				(1)

#define MSHC_HOST_VER4_ENABLE_BIT			BIT(12)
#define MSHC_HOST_VER4_ENABLE_FALSE			(0)
#define MSHC_HOST_VER4_ENABLE_TRUE			(1)

#define MSHC_CMD23_ENABLE_BIT				BIT(11)
#define MSHC_CMD23_ENABLE_FALSE				(0)
#define MSHC_CMD23_ENABLE_TRUE				(1)

#define MSHC_ADMA2_LEN_MODE_BIT				BIT(10)
#define MSHC_ADMA2_LEN_MODE_16			(0)
#define MSHC_ADMA2_LEN_MODE_26			(1)

#define MSHC_UHS2_IF_ENABLE_BIT				BIT(8)
#define MSHC_UHS2_IF_ENABLE_FALSE			(0)
#define MSHC_UHS2_IF_ENABLE_TRUE			(1)

#define MSHC_SAMPLE_CLK_SEL_BIT				BIT(7)
#define MSHC_SAMPLE_CLK_SEL_FALSE			(0)
#define MSHC_SAMPLE_CLK_SEL_TRUE			(1)

#define MSHC_EXEC_TUNING_BIT				BIT(6)
#define MSHC_EXEC_TUNING_FALSE				(0)
#define MSHC_EXEC_TUNING_TRUE				(1)

#define MSHC_DRV_STRENGTH_SEL_HBIT			(5)
#define MSHC_DRV_STRENGTH_SEL_LBIT			(4)
#define MSHC_DRV_STRENGTH_SEL_MASK			GENMASK(MSHC_DRV_STRENGTH_SEL_HBIT, MSHC_DRV_STRENGTH_SEL_LBIT)
#define MSHC_DRV_STRENGTH_SEL_TYPEB			(0x0 << MSHC_DRV_STRENGTH_SEL_LBIT)
#define MSHC_DRV_STRENGTH_SEL_TYPEA			(0x1 << MSHC_DRV_STRENGTH_SEL_LBIT)
#define MSHC_DRV_STRENGTH_SEL_TYPEC			(0x2 << MSHC_DRV_STRENGTH_SEL_LBIT)
#define MSHC_DRV_STRENGTH_SEL_TYPED			(0x3 << MSHC_DRV_STRENGTH_SEL_LBIT)

#define MSHC_SIGNALING_EN_BIT				BIT(3)
#define MSHC_SIGNALING_EN_V_3_3				(0)
#define MSHC_SIGNALING_EN_V_1_8				(1)

#define MSHC_UHS_MODE_SEL_HBIT				(2)
#define MSHC_UHS_MODE_SEL_LBIT				(0)
#define MSHC_UHS_MODE_SEL_MASK				GENMASK(MSHC_UHS_MODE_SEL_HBIT, MSHC_UHS_MODE_SEL_LBIT)
#define MSHC_UHS_MODE_SEL_SDR12				(0x0 << MSHC_UHS_MODE_SEL_LBIT)
#define MSHC_UHS_MODE_SEL_SDR25				(0x1 << MSHC_UHS_MODE_SEL_LBIT)
#define MSHC_UHS_MODE_SEL_SDR50				(0x2 << MSHC_UHS_MODE_SEL_LBIT)
#define MSHC_UHS_MODE_SEL_SDR104			(0x3 << MSHC_UHS_MODE_SEL_LBIT)
#define MSHC_UHS_MODE_SEL_DDR50				(0x4 << MSHC_UHS_MODE_SEL_LBIT)
#define MSHC_UHS_MODE_SEL_RSVD5				(0x5 << MSHC_UHS_MODE_SEL_LBIT)
#define MSHC_UHS_MODE_SEL_RSVD6				(0x6 << MSHC_UHS_MODE_SEL_LBIT)
#define MSHC_UHS_MODE_SEL_UHS2				(0x7 << MSHC_UHS_MODE_SEL_LBIT)

/* CAPABILITIES1_R */
#define MSHC_SLOT_TYPE_R_HBIT				(31)
#define MSHC_SLOT_TYPE_R_LBIT				(30)
#define MSHC_SLOT_TYPE_R_MASK				GENMASK(MSHC_SLOT_TYPE_R_HBIT, MSHC_SLOT_TYPE_R_LBIT)
#define MSHC_SLOT_TYPE_R_REMOVABLE_SLOT		(0x0 << MSHC_SLOT_TYPE_R_LBIT)
#define MSHC_SLOT_TYPE_R_EMBEDDED_SLOT		(0x1 << MSHC_SLOT_TYPE_R_LBIT)
#define MSHC_SLOT_TYPE_R_SHARED_SLOT		(0x2 << MSHC_SLOT_TYPE_R_LBIT)
#define MSHC_SLOT_TYPE_R_UHS2_EMBEDDED_SLOT	(0x3 << MSHC_SLOT_TYPE_R_LBIT)

#define MSHC_ASYNC_INT_SUPPORT_BIT			BIT(29)
#define MSHC_ASYNC_INT_SUPPORT_FALSE		(0)
#define MSHC_ASYNC_INT_SUPPORT_TRUE			(1)

#define MSHC_SYS_ADDR_64_V3_BIT				BIT(28)
#define MSHC_SYS_ADDR_64_V3_FALSE			(0)
#define MSHC_SYS_ADDR_64_V3_TRUE			(1)

#define MSHC_SYS_ADDR_64_V4_BIT				BIT(27)
#define MSHC_SYS_ADDR_64_V4_FALSE			(0)
#define MSHC_SYS_ADDR_64_V4_TRUE			(1)

#define MSHC_VOLT_18_BIT					BIT(26)
#define MSHC_VOLT_18_FALSE					(0)
#define MSHC_VOLT_18_TRUE					(1)

#define MSHC_VOLT_30_BIT					BIT(25)
#define MSHC_VOLT_30_FALSE					(0)
#define MSHC_VOLT_30_TRUE					(1)

#define MSHC_VOLT_33_BIT					BIT(24)
#define MSHC_VOLT_33_FALSE					(0)
#define MSHC_VOLT_33_TRUE					(1)

#define MSHC_SUS_RES_SUPPORT_BIT			BIT(23)
#define MSHC_SUS_RES_SUPPORT_FALSE			(0)
#define MSHC_SUS_RES_SUPPORT_TRUE			(1)

#define MSHC_SDMA_SUPPORT_BIT				BIT(22)
#define MSHC_SDMA_SUPPORT_FALSE				(0)
#define MSHC_SDMA_SUPPORT_TRUE				(1)

#define MSHC_HIGH_SPEED_SUPPORT_BIT			BIT(21)
#define MSHC_HIGH_SPEED_SUPPORT_FALSE		(0)
#define MSHC_HIGH_SPEED_SUPPORT_TRUE		(1)

#define MSHC_ADMA2_SUPPORT_BIT				BIT(19)
#define MSHC_ADMA2_SUPPORT_FALSE			(0)
#define MSHC_ADMA2_SUPPORT_TRUE				(1)

#define MSHC_EMBEDDED_8_BIT_BIT				BIT(18)
#define MSHC_EMBEDDED_8_BIT_FALSE			(0)
#define MSHC_EMBEDDED_8_BIT_TRUE			(1)

#define MSHC_MAX_BLK_LEN_HBIT				(17)
#define MSHC_MAX_BLK_LEN_LBIT				(16)
#define MSHC_MAX_BLK_LEN_MASK				GENMASK(MSHC_MAX_BLK_LEN_HBIT, MSHC_MAX_BLK_LEN_LBIT)
#define MSHC_MAX_BLK_LEN_ZERO				(0x0 << MSHC_MAX_BLK_LEN_LBIT)
#define MSHC_MAX_BLK_LEN_ONE				(0x1 << MSHC_MAX_BLK_LEN_LBIT)
#define MSHC_MAX_BLK_LEN_TWO				(0x2 << MSHC_MAX_BLK_LEN_LBIT)
#define MSHC_MAX_BLK_LEN_THREE				(0x3 << MSHC_MAX_BLK_LEN_LBIT)

#define MSHC_BASE_CLK_FREQ_HBIT				(15)
#define MSHC_BASE_CLK_FREQ_LBIT				(8)
#define MSHC_BASE_CLK_FREQ_MASK				GENMASK(MSHC_BASE_CLK_FREQ_HBIT, MSHC_BASE_CLK_FREQ_LBIT)

#define MSHC_TOUT_CLK_UNIT_BIT				BIT(7)
#define MSHC_TOUT_CLK_UNIT_KHZ				(0)
#define MSHC_TOUT_CLK_UNIT_MHZ				(1)

#define MSHC_TOUT_CLK_FREQ_HBIT				(5)
#define MSHC_TOUT_CLK_FREQ_LBIT				(0)
#define MSHC_TOUT_CLK_FREQ_MASK				GENMASK(MSHC_TOUT_CLK_FREQ_HBIT, MSHC_TOUT_CLK_FREQ_LBIT)

/* CAPABILITIES1_R */
#define MSHC_VDD2_18V_SUPPORT_BIT			BIT(28)
#define MSHC_VDD2_18V_SUPPORT_FALSE			(0)
#define MSHC_VDD2_18V_SUPPORT_TRUE			(1)

#define MSHC_ADMA3_SUPPORT_BIT				BIT(27)
#define MSHC_ADMA3_SUPPORT_FALSE			(0)
#define MSHC_ADMA3_SUPPORT_TRUE				(1)

#define MSHC_CLK_MUL_HBIT					(23)
#define MSHC_CLK_MUL_LBIT					(16)
#define MSHC_CLK_MUL_MASK					GENMASK(MSHC_CLK_MUL_HBIT, MSHC_CLK_MUL_LBIT)

#define MSHC_RE_TUNING_MODES_HBIT			(15)
#define MSHC_RE_TUNING_MODES_LBIT			(14)
#define MSHC_RE_TUNING_MODES_MASK			GENMASK(MSHC_RE_TUNING_MODES_HBIT, MSHC_RE_TUNING_MODES_LBIT)
#define MSHC_RE_TUNING_MODES_MODE1			(0x0 << MSHC_RE_TUNING_MODES_LBIT)
#define MSHC_RE_TUNING_MODES_MODE2			(0x1 << MSHC_RE_TUNING_MODES_LBIT)
#define MSHC_RE_TUNING_MODES_MODE3			(0x2 << MSHC_RE_TUNING_MODES_LBIT)
#define MSHC_RE_TUNING_MODES_RSVD_MODE		(0x3 << MSHC_RE_TUNING_MODES_LBIT)

#define MSHC_USE_TUNING_SDR50_BIT			BIT(13)
#define MSHC_USE_TUNING_SDR50_ZERO			(0)
#define MSHC_USE_TUNING_SDR50_ONE			(1)

#define MSHC_RETUNE_CNT_HBIT				(11)
#define MSHC_RETUNE_CNT_LBIT				(8)
#define MSHC_RETUNE_CNT_MASK				GENMASK(RETUNE_CNT_HBIT, RETUNE_CNT_LBIT)

#define MSHC_DRV_TYPED_BIT					BIT(6)
#define MSHC_DRV_TYPED_FALSE				(0)
#define MSHC_DRV_TYPED_TRUE					(1)

#define MSHC_DRV_TYPEC_BIT					BIT(5)
#define MSHC_DRV_TYPEC_FALSE				(0)
#define MSHC_DRV_TYPEC_TRUE					(1)

#define MSHC_DRV_TYPEA_BIT					BIT(4)
#define MSHC_DRV_TYPEA_FALSE				(0)
#define MSHC_DRV_TYPEA_TRUE					(1)

#define MSHC_UHS2_SUPPORT_BIT				BIT(3)
#define MSHC_UHS2_SUPPORT_FALSE				(0)
#define MSHC_UHS2_SUPPORT_TRUE				(1)

#define MSHC_DDR50_SUPPORT_BIT				BIT(2)
#define MSHC_DDR50_SUPPORT_FALSE			(0)
#define MSHC_DDR50_SUPPORT_TRUE				(1)

#define MSHC_SDR104_SUPPORT_BIT				BIT(1)
#define MSHC_SDR104_SUPPORT_FALSE			(0)
#define MSHC_SDR104_SUPPORT_TRUE			(1)

#define MSHC_SDR50_SUPPORT_BIT				BIT(0)
#define MSHC_SDR50_SUPPORT_FALSE			(0)
#define MSHC_SDR50_SUPPORT_TRUE				(1)

/* CURR_CAPABILITIES1_R */
#define MSHC_MAX_CUR_18V_HBIT				(23)
#define MSHC_MAX_CUR_18V_LBIT				(16)
#define MSHC_MAX_CUR_18V_MASK				GENMASK(MSHC_MAX_CUR_18V_HBIT, MSHC_MAX_CUR_18V_LBIT)

#define MSHC_MAX_CUR_30V_HBIT				(15)
#define MSHC_MAX_CUR_30V_LBIT				(8)
#define MSHC_MAX_CUR_30V_MASK				GENMASK(MSHC_MAX_CUR_30V_HBIT, MSHC_MAX_CUR_30V_LBIT)

#define MSHC_MAX_CUR_33V_HBIT				(7)
#define MSHC_MAX_CUR_33V_LBIT				(0)
#define MSHC_MAX_CUR_33V_MASK				GENMASK(MSHC_MAX_CUR_33V_HBIT, MSHC_MAX_CUR_33V_LBIT)

/* CURR_CAPABILITIES2_R */
#define MSHC_MAX_CUR_VDD2_18V_HBIT			(7)
#define MSHC_MAX_CUR_VDD2_18V_LBIT			(0)
#define MSHC_MAX_CUR_VDD2_18V_MASK			GENMASK(MSHC_MAX_CUR_VDD2_18V_HBIT, MSHC_MAX_CUR_VDD2_18V_LBIT)

/* FORCE_AUTO_CMD_STAT_R */
#define MSHC_FORCE_CMD_NOT_ISSUED_AUTO_CMD12_BIT		BIT(7)
#define MSHC_FORCE_CMD_NOT_ISSUED_AUTO_CMD12_FALSE		(0)
#define MSHC_FORCE_CMD_NOT_ISSUED_AUTO_CMD12_TRUE		(1)

#define MSHC_FORCE_AUTO_CMD_RESP_ERR_BIT				BIT(5)
#define MSHC_FORCE_AUTO_CMD_RESP_ERR_FALSE				(0)
#define MSHC_FORCE_AUTO_CMD_RESP_ERR_TRUE				(1)

#define MSHC_FORCE_AUTO_CMD_IDX_ERR_BIT					BIT(4)
#define MSHC_FORCE_AUTO_CMD_IDX_ERR_FALSE				(0)
#define MSHC_FORCE_AUTO_CMD_IDX_ERR_TRUE				(1)

#define MSHC_FORCE_AUTO_CMD_EBIT_ERR_BIT				BIT(3)
#define MSHC_FORCE_AUTO_CMD_EBIT_ERR_FALSE				(0)
#define MSHC_FORCE_AUTO_CMD_EBIT_ERR_TRUE				(1)

#define MSHC_FORCE_AUTO_CMD_CRC_ERR_BIT					BIT(2)
#define MSHC_FORCE_AUTO_CMD_CRC_ERR_FALSE				(0)
#define MSHC_FORCE_AUTO_CMD_CRC_ERR_TRUE				(1)

#define MSHC_FORCE_AUTO_CMD_TOUT_ERR_BIT				BIT(1)
#define MSHC_FORCE_AUTO_CMD_TOUT_ERR_FALSE				(0)
#define MSHC_FORCE_AUTO_CMD_TOUT_ERR_TRUE				(1)

#define MSHC_FORCE_AUTO_CMD12_NOT_EXEC_BIT				BIT(0)
#define MSHC_FORCE_AUTO_CMD12_NOT_EXEC_FALSE			(0)
#define MSHC_FORCE_AUTO_CMD12_NOT_EXEC_TRUE				(1)

/* FORCE_ERROR_INT_STAT_R */
#define	MSHC_FORCE_VENDOR_ERR3_BIT			BIT(15)
#define	MSHC_FORCE_VENDOR_ERR3_FALSE		(0)
#define	MSHC_FORCE_VENDOR_ERR3_TRUE			(1)

#define	MSHC_FORCE_VENDOR_ERR2_BIT			BIT(14)
#define	MSHC_FORCE_VENDOR_ERR2_FALSE		(0)
#define	MSHC_FORCE_VENDOR_ERR2_TRUE			(1)

#define	MSHC_FORCE_VENDOR_ERR1_BIT			BIT(13)
#define	MSHC_FORCE_VENDOR_ERR1_FALSE		(0)
#define	MSHC_FORCE_VENDOR_ERR1_TRUE			(1)

#define	MSHC_FORCE_BOOT_ACK_ERR_BIT			BIT(12)
#define	MSHC_FORCE_BOOT_ACK_ERR_FALSE		(0)
#define	MSHC_FORCE_BOOT_ACK_ERR_TRUE		(1)

#define	MSHC_FORCE_RESP_ERR_BIT				BIT(11)
#define	MSHC_FORCE_RESP_ERR_FALSE			(0)
#define	MSHC_FORCE_RESP_ERR_TRUE			(1)

#define	MSHC_FORCE_TUNING_ERR_BIT			BIT(10)
#define	MSHC_FORCE_TUNING_ERR_FALSE			(0)
#define	MSHC_FORCE_TUNING_ERR_TRUE			(1)

#define	MSHC_FORCE_ADMA_ERR_BIT				BIT(9)
#define	MSHC_FORCE_ADMA_ERR_FALSE			(0)
#define	MSHC_FORCE_ADMA_ERR_TRUE			(1)

#define	MSHC_FORCE_AUTO_CMD_ERR_BIT			BIT(8)
#define	MSHC_FORCE_AUTO_CMD_ERR_FALSE		(0)
#define	MSHC_FORCE_AUTO_CMD_ERR_TRUE		(1)

#define	MSHC_FORCE_CUR_LMT_ERR_BIT			BIT(7)
#define	MSHC_FORCE_CUR_LMT_ERR_FALSE		(0)
#define	MSHC_FORCE_CUR_LMT_ERR_TRUE			(1)

#define	MSHC_FORCE_DATA_END_BIT_ERR_BIT		BIT(6)
#define	MSHC_FORCE_DATA_END_BIT_ERR_FALSE	(0)
#define	MSHC_FORCE_DATA_END_BIT_ERR_TRUE	(1)

#define	MSHC_FORCE_DATA_CRC_ERR_BIT			BIT(5)
#define	MSHC_FORCE_DATA_CRC_ERR_FALSE		(0)
#define	MSHC_FORCE_DATA_CRC_ERR_TRUE		(1)

#define	MSHC_FORCE_DATA_TOUT_ERR_BIT		BIT(4)
#define	MSHC_FORCE_DATA_TOUT_ERR_FALSE		(0)
#define	MSHC_FORCE_DATA_TOUT_ERR_TRUE		(1)

#define	MSHC_FORCE_CMD_IDX_ERR_BIT			BIT(3)
#define	MSHC_FORCE_CMD_IDX_ERR_FALSE		(0)
#define	MSHC_FORCE_CMD_IDX_ERR_TRUE			(1)

#define	MSHC_FORCE_CMD_END_BIT_ERR_BIT		BIT(2)
#define	MSHC_FORCE_CMD_END_BIT_ERR_FALSE	(0)
#define	MSHC_FORCE_CMD_END_BIT_ERR_TRUE		(1)

#define	MSHC_FORCE_CMD_CRC_ERR_BIT			BIT(1)
#define	MSHC_FORCE_CMD_CRC_ERR_FALSE		(0)
#define	MSHC_FORCE_CMD_CRC_ERR_TRUE			(1)

#define	MSHC_FORCE_CMD_TOUT_ERR_BIT			BIT(0)
#define	MSHC_FORCE_CMD_TOUT_ERR_FALSE		(0)
#define	MSHC_FORCE_CMD_TOUT_ERR_TRUE		(1)

/* ADMA_ERR_STAT_R */
#define MSHC_ADMA_LEN_ERR_BIT				BIT(2)
#define MSHC_ADMA_LEN_ERR_NO_ERR			(0)
#define MSHC_ADMA_LEN_ERR_ERROR				(1)

#define MSHC_ADMA_ERR_STATES_HBIT			(1)
#define MSHC_ADMA_ERR_STATES_LBIT			(0)
#define MSHC_ADMA_ERR_STATES_MASK			GENMASK(MSHC_ADMA_ERR_STATES_HBIT, MSHC_ADMA_ERR_STATES_LBIT)
#define MSHC_ADMA_ERR_STATES_STOP			(0x0 << MSHC_ADMA_ERR_STATES_HBIT)
#define MSHC_ADMA_ERR_STATES_FDS			(0x1 << MSHC_ADMA_ERR_STATES_HBIT)
#define MSHC_ADMA_ERR_STATES_UNUSED			(0x2 << MSHC_ADMA_ERR_STATES_HBIT)
#define MSHC_ADMA_ERR_STATES_TFR			(0x3 << MSHC_ADMA_ERR_STATES_HBIT)

/* PRESET_INIT_R */
#define MSHC_INIT_DRV_SEL_VAL_HBIT			(15)
#define MSHC_INIT_DRV_SEL_VAL_LBIT			(14)
#define MSHC_INIT_DRV_SEL_VAL_MASK			GENMASK(MSHC_INIT_DRV_SEL_VAL_HBIT, MSHC_INIT_DRV_SEL_VAL_LBIT)
#define MSHC_INIT_DRV_SEL_VAL_TYPEB			(0x0 << MSHC_INIT_DRV_SEL_VAL_LBIT)
#define MSHC_INIT_DRV_SEL_VAL_TYPEA			(0x1 << MSHC_INIT_DRV_SEL_VAL_LBIT)
#define MSHC_INIT_DRV_SEL_VAL_TYPEC			(0x2 << MSHC_INIT_DRV_SEL_VAL_LBIT)
#define MSHC_INIT_DRV_SEL_VAL_TYPED			(0x3 << MSHC_INIT_DRV_SEL_VAL_LBIT)

#define MSHC_INIT_CLK_GEN_SEL_VAL_BIT		BIT(10)
#define MSHC_INIT_CLK_GEN_SEL_VAL_FALSE		(0)
#define MSHC_INIT_CLK_GEN_SEL_VAL_PROG		(1)

#define MSHC_INIT_FREQ_SEL_VAL_HBIT			(9)
#define MSHC_INIT_FREQ_SEL_VAL_LBIT			(0)
#define MSHC_INIT_FREQ_SEL_VAL_MASK			GENMASK(MSHC_INIT_FREQ_SEL_VAL_HBIT, MSHC_INIT_FREQ_SEL_VAL_LBIT)

/* PRESET_DS_R */
#define MSHC_DS_DRV_SEL_VAL_HBIT			(15)
#define MSHC_DS_DRV_SEL_VAL_LBIT			(14)
#define MSHC_DS_DRV_SEL_VAL_MASK			GENMASK(MSHC_DS_DRV_SEL_VAL_HBIT, MSHC_DS_DRV_SEL_VAL_LBIT)
#define MSHC_DS_DRV_SEL_VAL_TYPEB			(0x0 << MSHC_DS_DRV_SEL_VAL_LBIT)
#define MSHC_DS_DRV_SEL_VAL_TYPEA			(0x1 << MSHC_DS_DRV_SEL_VAL_LBIT)
#define MSHC_DS_DRV_SEL_VAL_TYPEC			(0x2 << MSHC_DS_DRV_SEL_VAL_LBIT)
#define MSHC_DS_DRV_SEL_VAL_TYPED			(0x3 << MSHC_DS_DRV_SEL_VAL_LBIT)

#define MSHC_DS_CLK_GEN_SEL_VAL_BIT			BIT(10)
#define MSHC_DS_CLK_GEN_SEL_VAL_FALSE		(0)
#define MSHC_DS_CLK_GEN_SEL_VAL_PROG		(1)

#define MSHC_DS_FREQ_SEL_VAL_HBIT			(9)
#define MSHC_DS_FREQ_SEL_VAL_LBIT			(0)
#define MSHC_DS_FREQ_SEL_VAL_MASK			GENMASK(MSHC_DS_FREQ_SEL_VAL_HBIT, MSHC_DS_FREQ_SEL_VAL_LBIT)

/* PRESET_HS_R */
#define MSHC_HS_DRV_SEL_VAL_HBIT			(15)
#define MSHC_HS_DRV_SEL_VAL_LBIT			(14)
#define MSHC_HS_DRV_SEL_VAL_MASK			GENMASK(MSHC_HS_DRV_SEL_VAL_HBIT, MSHC_HS_DRV_SEL_VAL_LBIT)
#define MSHC_HS_DRV_SEL_VAL_TYPEB			(0x0 << MSHC_HS_DRV_SEL_VAL_LBIT)
#define MSHC_HS_DRV_SEL_VAL_TYPEA			(0x1 << MSHC_HS_DRV_SEL_VAL_LBIT)
#define MSHC_HS_DRV_SEL_VAL_TYPEC			(0x2 << MSHC_HS_DRV_SEL_VAL_LBIT)
#define MSHC_HS_DRV_SEL_VAL_TYPED			(0x3 << MSHC_HS_DRV_SEL_VAL_LBIT)

#define MSHC_HS_CLK_GEN_SEL_VAL_BIT			BIT(10)
#define MSHC_HS_CLK_GEN_SEL_VAL_FALSE		(0)
#define MSHC_HS_CLK_GEN_SEL_VAL_PROG		(1)

#define MSHC_HS_FREQ_SEL_VAL_HBIT			(9)
#define MSHC_HS_FREQ_SEL_VAL_LBIT			(0)
#define MSHC_HS_FREQ_SEL_VAL_MASK			GENMASK(MSHC_HS_FREQ_SEL_VAL_HBIT, MSHC_HS_FREQ_SEL_VAL_LBIT)

/* PRESET_SDR12_R */
#define MSHC_SDR12_DRV_SEL_VAL_HBIT			(15)
#define MSHC_SDR12_DRV_SEL_VAL_LBIT			(14)
#define MSHC_SDR12_DRV_SEL_VAL_MASK			GENMASK(MSHC_SDR12_DRV_SEL_VAL_HBIT, MSHC_SDR12_DRV_SEL_VAL_LBIT)
#define MSHC_SDR12_DRV_SEL_VAL_TYPEB		(0x0 << MSHC_SDR12_DRV_SEL_VAL_LBIT)
#define MSHC_SDR12_DRV_SEL_VAL_TYPEA		(0x1 << MSHC_SDR12_DRV_SEL_VAL_LBIT)
#define MSHC_SDR12_DRV_SEL_VAL_TYPEC		(0x2 << MSHC_SDR12_DRV_SEL_VAL_LBIT)
#define MSHC_SDR12_DRV_SEL_VAL_TYPED		(0x3 << MSHC_SDR12_DRV_SEL_VAL_LBIT)

#define MSHC_SDR12_CLK_GEN_SEL_VAL_BIT		BIT(10)
#define MSHC_SDR12_CLK_GEN_SEL_VAL_FALSE	(0)
#define MSHC_SDR12_CLK_GEN_SEL_VAL_PROG		(1)

#define MSHC_SDR12_FREQ_SEL_VAL_HBIT		(9)
#define MSHC_SDR12_FREQ_SEL_VAL_LBIT		(0)
#define MSHC_SDR12_FREQ_SEL_VAL_MASK		GENMASK(MSHC_SDR12_FREQ_SEL_VAL_HBIT, MSHC_SDR12_FREQ_SEL_VAL_LBIT)

/* PRESET_SDR25_R */
#define MSHC_SDR25_DRV_SEL_VAL_HBIT			(15)
#define MSHC_SDR25_DRV_SEL_VAL_LBIT			(14)
#define MSHC_SDR25_DRV_SEL_VAL_MASK			GENMASK(MSHC_SDR25_DRV_SEL_VAL_HBIT, MSHC_SDR25_DRV_SEL_VAL_LBIT)
#define MSHC_SDR25_DRV_SEL_VAL_TYPEB		(0x0 << MSHC_SDR25_DRV_SEL_VAL_LBIT)
#define MSHC_SDR25_DRV_SEL_VAL_TYPEA		(0x1 << MSHC_SDR25_DRV_SEL_VAL_LBIT)
#define MSHC_SDR25_DRV_SEL_VAL_TYPEC		(0x2 << MSHC_SDR25_DRV_SEL_VAL_LBIT)
#define MSHC_SDR25_DRV_SEL_VAL_TYPED		(0x3 << MSHC_SDR25_DRV_SEL_VAL_LBIT)

#define MSHC_SDR25_CLK_GEN_SEL_VAL_BIT		BIT(10)
#define MSHC_SDR25_CLK_GEN_SEL_VAL_FALSE	(0)
#define MSHC_SDR25_CLK_GEN_SEL_VAL_PROG		(1)

#define MSHC_SDR25_FREQ_SEL_VAL_HBIT		(9)
#define MSHC_SDR25_FREQ_SEL_VAL_LBIT		(0)
#define MSHC_SDR25_FREQ_SEL_VAL_MASK		GENMASK(MSHC_SDR25_FREQ_SEL_VAL_HBIT, MSHC_SDR25_FREQ_SEL_VAL_LBIT)

/* PRESET_SDR50_R */
#define MSHC_SDR50_DRV_SEL_VAL_HBIT			(15)
#define MSHC_SDR50_DRV_SEL_VAL_LBIT			(14)
#define MSHC_SDR50_DRV_SEL_VAL_MASK			GENMASK(MSHC_SDR50_DRV_SEL_VAL_HBIT, MSHC_SDR50_DRV_SEL_VAL_LBIT)
#define MSHC_SDR50_DRV_SEL_VAL_TYPEB		(0x0 << MSHC_SDR50_DRV_SEL_VAL_LBIT)
#define MSHC_SDR50_DRV_SEL_VAL_TYPEA		(0x1 << MSHC_SDR50_DRV_SEL_VAL_LBIT)
#define MSHC_SDR50_DRV_SEL_VAL_TYPEC		(0x2 << MSHC_SDR50_DRV_SEL_VAL_LBIT)
#define MSHC_SDR50_DRV_SEL_VAL_TYPED		(0x3 << MSHC_SDR50_DRV_SEL_VAL_LBIT)

#define MSHC_SDR50_CLK_GEN_SEL_VAL_BIT		BIT(10)
#define MSHC_SDR50_CLK_GEN_SEL_VAL_FALSE	(0)
#define MSHC_SDR50_CLK_GEN_SEL_VAL_PROG		(1)

#define MSHC_SDR50_FREQ_SEL_VAL_HBIT		(9)
#define MSHC_SDR50_FREQ_SEL_VAL_LBIT		(0)
#define MSHC_SDR50_FREQ_SEL_VAL_MASK		GENMASK(MSHC_SDR50_FREQ_SEL_VAL_HBIT, MSHC_SDR50_FREQ_SEL_VAL_LBIT)

/* PRESET_SDR104_R */
#define MSHC_SDR104_DRV_SEL_VAL_HBIT		(15)
#define MSHC_SDR104_DRV_SEL_VAL_LBIT		(14)
#define MSHC_SDR104_DRV_SEL_VAL_MASK		GENMASK(MSHC_SDR104_DRV_SEL_VAL_HBIT, MSHC_SDR104_DRV_SEL_VAL_LBIT)
#define MSHC_SDR104_DRV_SEL_VAL_TYPEB		(0x0 << MSHC_SDR104_DRV_SEL_VAL_LBIT)
#define MSHC_SDR104_DRV_SEL_VAL_TYPEA		(0x1 << MSHC_SDR104_DRV_SEL_VAL_LBIT)
#define MSHC_SDR104_DRV_SEL_VAL_TYPEC		(0x2 << MSHC_SDR104_DRV_SEL_VAL_LBIT)
#define MSHC_SDR104_DRV_SEL_VAL_TYPED		(0x3 << MSHC_SDR104_DRV_SEL_VAL_LBIT)

#define MSHC_SDR104_CLK_GEN_SEL_VAL_BIT		BIT(10)
#define MSHC_SDR104_CLK_GEN_SEL_VAL_FALSE	(0)
#define MSHC_SDR104_CLK_GEN_SEL_VAL_PROG	(1)

#define MSHC_SDR104_FREQ_SEL_VAL_HBIT		(9)
#define MSHC_SDR104_FREQ_SEL_VAL_LBIT		(0)
#define MSHC_SDR104_FREQ_SEL_VAL_MASK		GENMASK(MSHC_SDR104_FREQ_SEL_VAL_HBIT, MSHC_SDR104_FREQ_SEL_VAL_LBIT)

/* PRESET_DDR50_R */
#define MSHC_DDR50_DRV_SEL_VAL_HBIT			(15)
#define MSHC_DDR50_DRV_SEL_VAL_LBIT			(14)
#define MSHC_DDR50_DRV_SEL_VAL_MASK			GENMASK(MSHC_DDR50_DRV_SEL_VAL_HBIT, MSHC_DDR50_DRV_SEL_VAL_LBIT)
#define MSHC_DDR50_DRV_SEL_VAL_TYPEB		(0x0 << MSHC_DDR50_DRV_SEL_VAL_LBIT)
#define MSHC_DDR50_DRV_SEL_VAL_TYPEA		(0x1 << MSHC_DDR50_DRV_SEL_VAL_LBIT)
#define MSHC_DDR50_DRV_SEL_VAL_TYPEC		(0x2 << MSHC_DDR50_DRV_SEL_VAL_LBIT)
#define MSHC_DDR50_DRV_SEL_VAL_TYPED		(0x3 << MSHC_DDR50_DRV_SEL_VAL_LBIT)

#define MSHC_DDR50_CLK_GEN_SEL_VAL_BIT		BIT(10)
#define MSHC_DDR50_CLK_GEN_SEL_VAL_FALSE	(0)
#define MSHC_DDR50_CLK_GEN_SEL_VAL_PROG		(1)

#define MSHC_DDR50_FREQ_SEL_VAL_HBIT		(9)
#define MSHC_DDR50_FREQ_SEL_VAL_LBIT		(0)
#define MSHC_DDR50_FREQ_SEL_VAL_MASK		GENMASK(MSHC_DDR50_FREQ_SEL_VAL_HBIT, MSHC_DDR50_FREQ_SEL_VAL_LBIT)

/* P_EMBEDDED_CNTRL */
#define MSHC_EMBEDDED_CNTRL_REG_OFFSET_ADDR_HBIT			(11)
#define MSHC_EMBEDDED_CNTRL_REG_OFFSET_ADDR_LBIT			(0)
#define MSHC_EMBEDDED_CNTRL_REG_OFFSET_ADDR_MASK			\
	GENMASK(MSHC_EMBEDDED_CNTRL_REG_OFFSET_ADDR_HBIT, MSHC_EMBEDDED_CNTRL_REG_OFFSET_ADDR_LBIT)

/* P_VENDOR_SPECIFIC_AREA */
#define MSHC_VENDOR_SPECIFIC_REG_OFFSET_ADDR_HBIT		(11)
#define MSHC_VENDOR_SPECIFIC_REG_OFFSET_ADDR_LBIT		(0)
#define MSHC_VENDOR_SPECIFIC_REG_OFFSET_ADDR_MASK		\
	GENMASK(MSHC_VENDOR_SPECIFIC_REG_OFFSET_ADDR_HBIT, MSHC_VENDOR_SPECIFIC_REG_OFFSET_ADDR_LBIT)

/* P_VENDOR2_SPECIFIC_AREA */
#define MSHC_CQE_REG_OFFSET_ADDR_HBIT		(11)
#define MSHC_CQE_REG_OFFSET_ADDR_LBIT		(0)
#define MSHC_CQE_REG_OFFSET_ADDR_MASK		\
	GENMASK(MSHC_CQE_REG_OFFSET_ADDR_HBIT, MSHC_CQE_REG_OFFSET_ADDR_LBIT)

/* SLOT_INTR_STATUS_R */
#define MSHC_INTR_SLOT_HBIT					(7)
#define MSHC_INTR_SLOT_LBIT					(0)
#define MSHC_INTR_SLOT_MASK					GENMASK(MSHC_INTR_SLOT_HBIT, MSHC_INTR_SLOT_LBIT)

/* HOST_CNTRL_VERS_R */
#define MSHC_VENDOR_VERSION_NUM_HBIT		(15)
#define MSHC_VENDOR_VERSION_NUM_LBIT		(8)
#define MSHC_VENDOR_VERSION_NUM_MASK		GENMASK(MSHC_VENDOR_VERSION_NUM_HBIT, MSHC_VENDOR_VERSION_NUM_LBIT)

#define MSHC_SPEC_VERSION_NUM_HBIT			(7)
#define MSHC_SPEC_VERSION_NUM_LBIT			(0)
#define MSHC_SPEC_VERSION_NUM_MASK			GENMASK(MSHC_SPEC_VERSION_NUM_HBIT, MSHC_SPEC_VERSION_NUM_LBIT)
#define MSHC_SPEC_VERSION_NUM_1_0_0			(0x0 << MSHC_SPEC_VERSION_NUM_LBIT)
#define MSHC_SPEC_VERSION_NUM_2_0_0			(0x1 << MSHC_SPEC_VERSION_NUM_LBIT)
#define MSHC_SPEC_VERSION_NUM_3_0_0			(0x2 << MSHC_SPEC_VERSION_NUM_LBIT)
#define MSHC_SPEC_VERSION_NUM_4_0_0			(0x3 << MSHC_SPEC_VERSION_NUM_LBIT)
#define MSHC_SPEC_VERSION_NUM_4_1_0			(0x4 << MSHC_SPEC_VERSION_NUM_LBIT)
#define MSHC_SPEC_VERSION_NUM_4_2_0			(0x5 << MSHC_SPEC_VERSION_NUM_LBIT)

/* EMBEDDED_CTRL_R */
#define MSHC_BACK_END_PWR_CTRL_HBIT			(30)
#define MSHC_BACK_END_PWR_CTRL_LBIT			(24)
#define MSHC_BACK_END_PWR_CTRL_MASK			GENMASK(MSHC_BACK_END_PWR_CTRL_HBIT, MSHC_BACK_END_PWR_CTRL_LBIT)
#define MSHC_BACK_END_PWR_CTRL_DEV1			(0x1 << MSHC_BACK_END_PWR_CTRL_LBIT)
#define MSHC_BACK_END_PWR_CTRL_DEV2			(0x1 << (MSHC_BACK_END_PWR_CTRL_LBIT + 1))
#define MSHC_BACK_END_PWR_CTRL_DEV3			(0x1 << (MSHC_BACK_END_PWR_CTRL_LBIT + 2))
#define MSHC_BACK_END_PWR_CTRL_DEV4			(0x1 << (MSHC_BACK_END_PWR_CTRL_LBIT + 3))
#define MSHC_BACK_END_PWR_CTRL_DEV5			(0x1 << (MSHC_BACK_END_PWR_CTRL_LBIT + 4))
#define MSHC_BACK_END_PWR_CTRL_DEV6			(0x1 << (MSHC_BACK_END_PWR_CTRL_LBIT + 5))
#define MSHC_BACK_END_PWR_CTRL_DEV7			(0x1 << (MSHC_BACK_END_PWR_CTRL_LBIT + 6))
#define MSHC_BACK_END_PWR_CTRL_POWER_OFF	(0)
#define MSHC_BACK_END_PWR_CTRL_POWER_SUP	(1)

#define MSHC_INT_PIN_SEL_HBIT				(22)
#define MSHC_INT_PIN_SEL_LBIT				(20)
#define MSHC_INT_PIN_SEL_MASK				GENMASK(MSHC_INT_PIN_SEL_HBIT, MSHC_INT_PIN_SEL_LBIT)
#define MSHC_INT_PIN_SEL_INT_DISABLE		(0x0 << MSHC_INT_PIN_SEL_LBIT)
#define MSHC_INT_PIN_SEL_INT_A				(0x1 << MSHC_INT_PIN_SEL_LBIT)
#define MSHC_INT_PIN_SEL_INT_B				(0x1 << (MSHC_INT_PIN_SEL_LBIT + 1))
#define MSHC_INT_PIN_SEL_INT_C				(0x1 << (MSHC_INT_PIN_SEL_LBIT + 2))

#define MSHC_CLK_PIN_SEL_HBIT				(18)
#define MSHC_CLK_PIN_SEL_LBIT				(16)
#define MSHC_CLK_PIN_SEL_MASK				GENMASK(MSHC_CLK_PIN_SEL_HBIT, MSHC_CLK_PIN_SEL_LBIT)
#define MSHC_CLK_PIN_SEL_CLK_DISABLE		(0x0 << MSHC_CLK_PIN_SEL_LBIT)
#define MSHC_CLK_PIN_SEL_CLK1				(0x1 << MSHC_CLK_PIN_SEL_LBIT)
#define MSHC_CLK_PIN_SEL_CLK2				(0x2 << MSHC_CLK_PIN_SEL_LBIT)
#define MSHC_CLK_PIN_SEL_CLK3				(0x3 << MSHC_CLK_PIN_SEL_LBIT)
#define MSHC_CLK_PIN_SEL_CLK4				(0x4 << MSHC_CLK_PIN_SEL_LBIT)
#define MSHC_CLK_PIN_SEL_CLK5				(0x5 << MSHC_CLK_PIN_SEL_LBIT)
#define MSHC_CLK_PIN_SEL_CLK6				(0x6 << MSHC_CLK_PIN_SEL_LBIT)
#define MSHC_CLK_PIN_SEL_CLK7				(0x7 << MSHC_CLK_PIN_SEL_LBIT)

#define MSHC_BUS_WIDTH_PRESET_HBIT			(14)
#define MSHC_BUS_WIDTH_PRESET_LBIT			(8)
#define MSHC_BUS_WIDTH_PRESET_MASK			GENMASK(MSHC_BUS_WIDTH_PRESET_HBIT, MSHC_BUS_WIDTH_PRESET_LBIT)
#define MSHC_BUS_WIDTH_PRESET_DEV1			(0x1 << MSHC_BUS_WIDTH_PRESET_LBIT)
#define MSHC_BUS_WIDTH_PRESET_DEV2			(0x1 << (MSHC_BUS_WIDTH_PRESET_LBIT + 1))
#define MSHC_BUS_WIDTH_PRESET_DEV3			(0x1 << (MSHC_BUS_WIDTH_PRESET_LBIT + 2))
#define MSHC_BUS_WIDTH_PRESET_DEV4			(0x1 << (MSHC_BUS_WIDTH_PRESET_LBIT + 3))
#define MSHC_BUS_WIDTH_PRESET_DEV5			(0x1 << (MSHC_BUS_WIDTH_PRESET_LBIT + 4))
#define MSHC_BUS_WIDTH_PRESET_DEV6			(0x1 << (MSHC_BUS_WIDTH_PRESET_LBIT + 5))
#define MSHC_BUS_WIDTH_PRESET_DEV7			(0x1 << (MSHC_BUS_WIDTH_PRESET_LBIT + 6))
#define MSHC_BUS_WIDTH_PRESET_4				(0)
#define MSHC_BUS_WIDTH_PRESET_8				(1)

#define MSHC_NUM_INT_PIN_HBIT				(5)
#define MSHC_NUM_INT_PIN_LBIT				(4)
#define MSHC_NUM_INT_PIN_MASK				GENMASK(MSHC_NUM_INT_PIN_HBIT, MSHC_NUM_INT_PIN_LBIT)
#define MSHC_NUM_INT_PIN_NOT_SUPPORT		(0x0 << MSHC_NUM_INT_PIN_LBIT)
#define MSHC_NUM_INT_PIN_INT_A				(0x1 << MSHC_NUM_INT_PIN_LBIT)
#define MSHC_NUM_INT_PIN_INT_A_B			(0x2 << MSHC_NUM_INT_PIN_LBIT)
#define MSHC_NUM_INT_PIN_INT_A_B_C			(0x3 << MSHC_NUM_INT_PIN_LBIT)

#define MSHC_NUM_CLK_PIN_HBIT				(2)
#define MSHC_NUM_CLK_PIN_LBIT				(0)
#define MSHC_NUM_CLK_PIN_MASK				GENMASK(MSHC_NUM_CLK_PIN_HBIT, MSHC_NUM_CLK_PIN_LBIT)
#define MSHC_NUM_CLK_PIN_NOT_SUPPORT		(0x0 << MSHC_NUM_CLK_PIN_LBIT)
#define MSHC_NUM_CLK_PIN_1_SDCLK			(0x1 << MSHC_NUM_CLK_PIN_LBIT)
#define MSHC_NUM_CLK_PIN_2_SDCLK			(0x2 << MSHC_NUM_CLK_PIN_LBIT)
#define MSHC_NUM_CLK_PIN_3_SDCLK			(0x3 << MSHC_NUM_CLK_PIN_LBIT)
#define MSHC_NUM_CLK_PIN_4_SDCLK			(0x4 << MSHC_NUM_CLK_PIN_LBIT)
#define MSHC_NUM_CLK_PIN_5_SDCLK			(0x5 << MSHC_NUM_CLK_PIN_LBIT)
#define MSHC_NUM_CLK_PIN_6_SDCLK			(0x6 << MSHC_NUM_CLK_PIN_LBIT)
#define MSHC_NUM_CLK_PIN_7_SDCLK			(0x7 << MSHC_NUM_CLK_PIN_LBIT)

/* CQVER */
#define MSHC_EMMC_VER_MAJOR_HBIT			(11)
#define MSHC_EMMC_VER_MAJOR_LBIT			(8)
#define MSHC_EMMC_VER_MAJOR_MASK			GENMASK(MSHC_EMMC_VER_MAJOR_HBIT, MSHC_EMMC_VER_MAJOR_LBIT)

#define MSHC_EMMC_VER_MINOR_HBIT			(7)
#define MSHC_EMMC_VER_MINOR_LBIT			(4)
#define MSHC_EMMC_VER_MINOR_MASK			GENMASK(MSHC_EMMC_VER_MINOR_HBIT, MSHC_EMMC_VER_MINOR_LBIT)

#define MSHC_EMMC_VER_SUFFIX_HBIT			(3)
#define MSHC_EMMC_VER_SUFFIX_LBIT			(0)
#define MSHC_EMMC_VER_SUFFIX_MASK			GENMASK(MSHC_EMMC_VER_SUFFIX_HBIT, MSHC_EMMC_VER_SUFFIX_LBIT)

/* CQCAP */
#define MSHC_ITCFMUL_HBIT					(15)
#define MSHC_ITCFMUL_LBIT					(12)
#define MSHC_ITCFMUL_MASK					GENMASK(MSHC_ITCFMUL_HBIT, MSHC_ITCFMUL_LBIT)
#define MSHC_ITCFMUL_1KHZ					(0x0 << MSHC_ITCFMUL_LBIT)
#define MSHC_ITCFMUL_10KHZ					(0x1 << MSHC_ITCFMUL_LBIT)
#define MSHC_ITCFMUL_100KHZ					(0x2 << MSHC_ITCFMUL_LBIT)
#define MSHC_ITCFMUL_1MHZ					(0x3 << MSHC_ITCFMUL_LBIT)
#define MSHC_ITCFMUL_10MHZ					(0x4 << MSHC_ITCFMUL_LBIT)

#define MSHC_ITCFVAL_HBIT					(9)
#define MSHC_ITCFVAL_LBIT					(0)
#define MSHC_ITCFVAL_MASK					GENMASK(MSHC_ITCFVAL_HBIT, MSHC_ITCFVAL_LBIT)

/* CQCFG */
#define MSHC_DCMD_EN_BIT					BIT(12)
#define MSHC_DCMD_DATA						(0)
#define MSHC_DCMD_CMD						(1)

#define MSHC_TASK_DESC_SIZE_BIT				BIT(8)
#define MSHC_TASK_DESC_SIZE_64				(0)
#define MSHC_TASK_DESC_SIZE_128				(1)

#define MSHC_CQ_EN_BIT						BIT(0)
#define MSHC_CQ_DISABLE						(0)
#define MSHC_CQ_ENABLE						(1)

/* CQCTL */
#define MSHC_CLR_ALL_TASKS_BIT				BIT(8)
#define MSHC_CLR_ALL_TASKS_DISABLE			(0)
#define MSHC_CLR_ALL_TASKS_ENABLE			(1)

#define MSHC_HALT_BIT						BIT(0)
#define MSHC_HALT_ENABLE					(0)
#define MSHC_HALT_DISABLE					(1)

/* CQIS */
#define MSHC_TCL_BIT						BIT(3)
#define MSHC_TCL_FALSE						(0)
#define MSHC_TCL_TRUE						(1)

#define MSHC_RED_BIT						BIT(2)
#define MSHC_RED_FALSE						(0)
#define MSHC_RED_TRUE						(1)

#define MSHC_TCC_BIT						BIT(1)
#define MSHC_TCC_FALSE						(0)
#define MSHC_TCC_TRUE						(1)

#define MSHC_HAC_BIT						BIT(0)
#define MSHC_HAC_FALSE						(0)
#define MSHC_HAC_TRUE						(1)

/* CQISE */
#define MSHC_TCL_STE_BIT					BIT(3)
#define MSHC_TCL_STE_DISABLE				(0)
#define MSHC_TCL_STE_ENABLE					(1)

#define MSHC_RED_STE_BIT					BIT(2)
#define MSHC_RED_STE_DISABLE				(0)
#define MSHC_RED_STE_ENABLE					(1)

#define MSHC_TCC_STE_BIT					BIT(1)
#define MSHC_TCC_STE_DISABLE				(0)
#define MSHC_TCC_STE_ENABLE					(1)

#define MSHC_HAC_STE_BIT					BIT(0)
#define MSHC_HAC_STE_DISABLE				(0)
#define MSHC_HAC_STE_ENABLE					(1)

/* CQISGE */
#define MSHC_TCL_SGE_BIT					BIT(3)
#define MSHC_TCL_SGE_DISABLE				(0)
#define MSHC_TCL_SGE_ENABLE					(1)

#define MSHC_RED_SGE_BIT					BIT(2)
#define MSHC_RED_SGE_DISABLE				(0)
#define MSHC_RED_SGE_ENABLE					(1)

#define MSHC_TCC_SGE_BIT					BIT(1)
#define MSHC_TCC_SGE_DISABLE				(0)
#define MSHC_TCC_SGE_ENABLE					(1)

#define MSHC_HAC_SGE_BIT					BIT(0)
#define MSHC_HAC_SGE_DISABLE				(0)
#define MSHC_HAC_SGE_ENABLE					(1)

/* CQIC */
#define MSHC_INTC_EN_BIT					BIT(31)
#define MSHC_INTC_ENABLE					(0)
#define MSHC_INTC_DISABLE					(1)

#define MSHC_INTC_STAT_BIT					BIT(20)
#define MSHC_INTC_STAT_NOT_COUNTED			(0)
#define MSHC_INTC_STAT_COUNTED				(1)

#define MSHC_INTC_RST_BIT					BIT(16)
#define MSHC_INTC_RST_DISABLE				(0)
#define MSHC_INTC_RST_ENABLE				(1)

#define MSHC_INTC_TH_WEN_BIT				BIT(15)
#define MSHC_INTC_TH_WEN_DISABLE			(0)
#define MSHC_INTC_TH_WEN_ENABLE				(1)

#define MSHC_INTC_TH_HBIT					(12)
#define MSHC_INTC_TH_LBIT					(8)
#define MSHC_INTC_TH_MASK					GENMASK(MSHC_INTC_TH_HBIT, MSHC_INTC_TH_LBIT)

#define MSHC_TOUT_VAL_WEN_BIT				BIT(7)
#define MSHC_TOUT_VAL_WEN_DISABLE			(0)
#define MSHC_TOUT_VAL_WEN_ENABLE			(1)

#define MSHC_TOUT_VAL_HBIT					(6)
#define MSHC_TOUT_VAL_LBIT					(0)
#define MSHC_TOUT_VAL_MASK					GENMASK(MSHC_TOUT_VAL_HBIT, MSHC_TOUT_VAL_LBIT)

/* CQSSC1 */
#define MSHC_SQSCMD_BLK_CNT_HBIT			(19)
#define MSHC_SQSCMD_BLK_CNT_LBIT			(16)
#define MSHC_SQSCMD_BLK_CNT_MASK			GENMASK(MSHC_SQSCMD_BLK_CNT_HBIT, MSHC_SQSCMD_BLK_CNT_LBIT)

#define MSHC_SQSCMD_IDLE_TMR_HBIT			(15)
#define MSHC_SQSCMD_IDLE_TMR_LBIT			(0)
#define MSHC_SQSCMD_IDLE_TMR_MASK			GENMASK(MSHC_SQSCMD_IDLE_TMR_HBIT, MSHC_SQSCMD_IDLE_TMR_LBIT)

/* CQSSC1 */
#define MSHC_SQSCMD_RCA_HBIT				(15)
#define MSHC_SQSCMD_RCA_LBIT				(0)
#define MSHC_SQSCMD_RCA_MASK				GENMASK(MSHC_SQSCMD_RCA_HBIT, MSHC_SQSCMD_RCA_LBIT)

/* CQTERRI */
#define MSHC_TRANS_ERR_FIFLDS_VALID_BIT		BIT(31)
#define MSHC_TRANS_ERR_FIFLDS_VALID_IGNORE	(0)
#define MSHC_TRANS_ERR_FIFLDS_VALID_CHECK	(1)

#define MSHC_TRANS_ERR_TASKID_HBIT			(28)
#define MSHC_TRANS_ERR_TASKID_LBIT			(24)
#define MSHC_TRANS_ERR_TASKID_MASK			GENMASK(MSHC_TRANS_ERR_TASKID_HBIT, MSHC_TRANS_ERR_TASKID_LBIT)

#define MSHC_TRANS_ERR_CMD_INDX_HBIT		(21)
#define MSHC_TRANS_ERR_CMD_INDX_LBIT		(16)
#define MSHC_TRANS_ERR_CMD_INDX_MASK		GENMASK(MSHC_TRANS_ERR_CMD_INDX_HBIT, MSHC_TRANS_ERR_CMD_INDX_LBIT)

#define MSHC_RESP_ERR_FIELDS_VAILD_BIT		BIT(15)
#define MSHC_RESP_ERR_FIFLDS_VALID_IGNORE	(0)
#define MSHC_RESP_ERR_FIFLDS_VALID_CHECK	(1)

#define MSHC_RESP_ERR_TASKID_HBIT			(18)
#define MSHC_RESP_ERR_TASKID_LBIT			(14)
#define MSHC_RESP_ERR_TASKID_MASK			GENMASK(MSHC_RESP_ERR_TASKID_HBIT, MSHC_RESP_ERR_TASKID_LBIT)

#define MSHC_RESP_ERR_CMD_INDX_HBIT			(5)
#define MSHC_RESP_ERR_CMD_INDX_LBIT			(0)
#define MSHC_RESP_ERR_CMD_INDX_MASK			GENMASK(MSHC_RESP_ERR_CMD_INDX_HBIT, MSHC_RESP_ERR_CMD_INDX_LBIT)

/* CQCRI */
#define MSHC_CMD_RESP_INDX_HBIT				(5)
#define MSHC_CMD_RESP_INDX_LBIT				(0)
#define MSHC_CMD_RESP_INDX_MASK				GENMASK(MSHC_CMD_RESP_INDX_HBIT, MSHC_CMD_RESP_INDX_LBIT)

/* EMMC_CTRL_R */
#define MSHC_CQE_PREFETCH_DISABLE_BIT		BIT(10)
#define MSHC_CQE_PREFETCH_ENABLE			(0)
#define MSHC_CQE_PREFETCH_DISABLE			(1)

#define MSHC_CQE_ALGO_SEL_BIT							BIT(9)
#define MSHC_CQE_ALGO_SEL_PRI_REORDER_PLUS_FCFS			(0)
#define MSHC_CQE_ALGO_SEL_FCFS_ONLY						(1)

#define MSHC_ENH_STROBE_ENABLE_BIT			BIT(8)
#define MSHC_ENH_STROBE_NO_STB_FOR_CMD		(0)
#define MSHC_ENH_STROBE_ENH_STB_FOR_CMD		(1)

#define MSHC_DISABLE_DATA_CRC_CHK_BIT		BIT(1)
#define MSHC_DISABLE_DATA_CRC_CHK_ENABLE	(0)
#define MSHC_DISABLE_DATA_CRC_CHK_DISABLE	(1)

#define MSHC_CARD_IS_EMMC_BIT				BIT(0)
#define MSHC_CARD_IS_EMMC_NON_EMMC_CARD		(0)
#define MSHC_CARD_IS_EMMC_EMMC_CARD			(1)

/* BOOT_CTRL_R */
#define MSHC_BOOT_TOUT_CNT_HBIT				(15)
#define MSHC_BOOT_TOUT_CNT_LBIT				(12)
#define MSHC_BOOT_TOUT_CNT_MASK				GENMASK(MSHC_BOOT_TOUT_CNT_HBIT, MSHC_BOOT_TOUT_CNT_LBIT)

#define MSHC_BOOT_ACK_ENABLE_BIT			BIT(8)
#define MSHC_BOOT_ACK_ENABLE_FALSE			(0)
#define MSHC_BOOT_ACK_ENABLE_TRUE			(1)

#define MSHC_VALIDATE_BOOT_BIT				BIT(7)
#define MSHC_VALIDATE_BOOT_FALSE			(0)
#define MSHC_VALIDATE_BOOT_TRUE				(1)

#define MSHC_MAN_BOOT_EN_BIT				BIT(0)
#define MSHC_MAN_BOOT_DIS					(0)
#define MSHC_MAN_BOOT_EN					(1)

/* GP_IN_R */


/* GP_OUT_R */



#endif	/*_DW_MSHC_REGS_H_*/
