COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc_common.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc_host.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc_sd.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc_emmc.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc_test.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/transfer/dw_mshc_transfer_pio.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/transfer/dw_mshc_transfer_sdma.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/transfer/dw_mshc_transfer_adma2.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/transfer/dw_mshc_transfer_adma3.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/transfer/dw_mshc_transfer_cqe.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/mshc_tests.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc_sd_test_case.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc_emmc_test_case.o
COBJS-$(CONFIG_MSHC_TEST) +=$(BOARD_TM_MSHC_DIR)/dw_mshc_other_test_case.o

