#!/bin/sh
#
# bluetooth    Bluetooth subsystem starting and stopping
#
# chkconfig: - 25 90
# description: Bluetooth subsystem
#

# Source function library.
. /etc/rc.d/init.d/functions

# Source Bluetooth configuration.
#. /etc/sysconfig/bluetooth

prog="Bluetooth"
UART_CONF="/etc/bluetooth/uart"
USB_CONF="/etc/bluetooth/usb"
# Bluez Library
export PATH=$PATH:/opt/bluez/bin:/opt/bluez/sbin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/bluez/lib

start() 
{
        echo -n "Starting $prog: "
	if [ -d /sys/class/bluetooth/hci0 ]
	then
        	hcid -f /etc/bluetooth/hcid.conf
		sdpd
		pand --listen --role NAP
		hciconfig hci0 up
		check_status
		exit 0
	fi
	[ -d /sys/class/bluetooth/hci0 ]
	check_status
	exit 1
}

stop() 
{
        echo -n $"Shutting down $prog: "
	killproc hcid
	killproc sdpd
        echo
}

# See how we were called.
case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  restart|reload)
	stop
	start
	;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0
