#!/bin/sh

start() {
	udhcpc -n -q -S -i eth0 -s /usr/bin/udhcpc_upgrade_action.sh -p /tmp/udhcpc-upgrade-eth0.pid
}

case "$1" in
	start)
		start
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac

exit $?
