######################################################################
# Automatically generated by qmake (1.07a) Tue Nov 25 19:07:18 2014
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += competitor.h date.h human.h judge.h machcompetitor.h
SOURCES += competitor.cpp \
           date.cpp \
           human.cpp \
           judge.cpp \
           machcompetitor.cpp \
           main.cpp
